variables:
  _DotNetCoreRuntimeVersion: 5.0.11        # matches with SDK v. 5.0.402
  _WindowsSdkPackageVersion: 10.0.18362.22 # matches with one consumed in WindowsAppSdk

name: $(MajorVersion).$(MinorVersion).$(PatchVersion)$(PrereleaseVersion).$(date:yyMMdd)$(rev:.r)

stages:
- template: CsWinRT-BuildAndTest-Stage.yml

- template: CsWinRT-PublishToNuget-Stage.yml

# if we are doing a release build, publish the build to Maestro
#- ${{ if eq( '$(PrereleaseVersion)', '') }}:
- template: Maestro-PublishBuildToMaestro-Steps.yml
  parameters: 
    AssetNames: Microsoft.Windows.CsWinRT;CsWinRT.Dependency.DotNetCoreSdkVersion;CsWinRT.Dependency.DotNetCoreRuntimeVersion;CsWinRT.Dependency.WindowsSdkPackageVersion
    AssetVersions: $(NugetVersion);$(Net5.Sdk.Version);$(_DotNetCoreRuntimeVersion);$(_WindowsSdkPackageVersion)