// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using AsmResolver.DotNet;
using AsmResolver.DotNet.Signatures;
using WindowsRuntime.ProjectionWriter.Builders;
using WindowsRuntime.ProjectionWriter.Factories.Callbacks;
using WindowsRuntime.ProjectionWriter.Generation;
using WindowsRuntime.ProjectionWriter.Helpers;
using WindowsRuntime.ProjectionWriter.Metadata;
using WindowsRuntime.ProjectionWriter.Models;
using WindowsRuntime.ProjectionWriter.Resolvers;
using WindowsRuntime.ProjectionWriter.Writers;

namespace WindowsRuntime.ProjectionWriter.Factories;

/// <summary>
/// Helper writers for assembly attributes, metadata attributes, file headers, and
/// other infrastructure that runs at the top or bottom of every emitted projection
/// file.
/// </summary>
internal static class MetadataAttributeFactory
{
    /// <summary>
    /// Returns the version string embedded in the banner comment of generated files.
    /// MSBuild and defaults to <c>0.0.0-private.0</c>).
    /// We read the writer assembly's <see cref="AssemblyInformationalVersionAttribute"/>
    /// (set via <c>$(InformationalVersion)</c>) and strip any SourceLink commit-sha suffix
    /// after a '+' so the banner is reproducible across rebuilds of the same source.
    /// </summary>
    internal static string GetVersionString()
    {
        Assembly asm = typeof(ProjectionFileBuilder).Assembly;
        AssemblyInformationalVersionAttribute? attr =
            (AssemblyInformationalVersionAttribute?)Attribute.GetCustomAttribute(
                asm, typeof(AssemblyInformationalVersionAttribute));
        string version = attr?.InformationalVersion ?? "0.0.0-private.0";
        int plus = version.IndexOf('+');
        return plus >= 0 ? version[..plus] : version;
    }

    /// <summary>
    /// Writes the standard auto-generated banner comment (no <c>using</c> imports, no pragmas).
    /// Used for the leaner <c>WinRT_Module.cs</c> / <c>GeneratedInterfaceIIDs.cs</c> /
    /// <c>Resources/Base/*.cs</c> output prelude. Distinct from
    /// <see cref="ProjectionWriterExtensions.WriteFileHeader"/>, which also emits the canonical
    /// <c>using</c> imports + suppression pragmas.
    /// </summary>
    /// <param name="writer">The writer to emit the banner to.</param>
    public static void WriteFileHeader(IndentedTextWriter writer)
    {
        writer.WriteLine(isMultiline: true, $$"""
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This file was generated by cswinrt.exe version {{GetVersionString()}}
            //
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------
            """);
    }

    /// <summary>
    /// Convenience overload of <see cref="WriteFileHeader(IndentedTextWriter)"/> that leases an
    /// <see cref="IndentedTextWriter"/> from <see cref="IndentedTextWriterPool"/>, emits the
    /// auto-generated banner into it, and returns the resulting string.
    /// </summary>
    /// <returns>The emitted auto-generated banner.</returns>
    public static string GetFileHeader()
    {
        using IndentedTextWriterOwner writerOwner = IndentedTextWriterPool.GetOrCreate();
        IndentedTextWriter writer = writerOwner.Writer;
        WriteFileHeader(writer);
        return writer.ToString();
    }

    /// <summary>
    /// Writes a <c>[WindowsRuntimeMetadata("&lt;stem&gt;")]</c> attribute decorating <paramref name="type"/> with its source <c>.winmd</c> module name.
    /// </summary>
    /// <param name="writer">The writer to emit to.</param>
    /// <param name="type">The type definition.</param>
    /// <param name="cache">The metadata cache used to resolve the source module path.</param>
    public static void WriteWinRTMetadataAttribute(IndentedTextWriter writer, TypeDefinition type, MetadataCache cache)
    {
        WriteWinRTMetadataAttributeBody(writer, type, cache);
        writer.WriteLine();
    }

    /// <inheritdoc cref="WriteWinRTMetadataAttribute(IndentedTextWriter, TypeDefinition, MetadataCache)"/>
    /// <returns>A callback emitting the attribute body (no trailing newline) so it can be interpolated into a multiline template.</returns>
    public static WriteWinRTMetadataAttributeCallback WriteWinRTMetadataAttribute(TypeDefinition type, MetadataCache cache)
    {
        return new(type, cache);
    }

    /// <summary>
    /// Writes just the attribute body (no trailing newline) for <see cref="WriteWinRTMetadataAttribute(IndentedTextWriter, TypeDefinition, MetadataCache)"/>.
    /// Used by the callback variant to allow the attribute to be inlined inside a multiline raw-string template line.
    /// </summary>
    internal static void WriteWinRTMetadataAttributeBody(IndentedTextWriter writer, TypeDefinition type, MetadataCache cache)
    {
        string path = cache.GetSourcePath(type);
        string stem = string.IsNullOrEmpty(path) ? string.Empty : Path.GetFileNameWithoutExtension(path);
        writer.Write($"[WindowsRuntimeMetadata(\"{stem}\")]");
    }

    /// <summary>
    /// Writes a <c>[WindowsRuntimeMetadataTypeName]</c> attribute carrying the WinRT type name string.
    /// </summary>
    /// <param name="writer">The writer to emit to.</param>
    /// <param name="context">The active emit context.</param>
    /// <param name="type">The type definition.</param>
    public static void WriteWinRTMetadataTypeNameAttribute(IndentedTextWriter writer, ProjectionEmitContext context, TypeDefinition type)
    {
        WriteWinRTMetadataTypeNameAttributeBody(writer, context, type);
        writer.WriteLine();
    }

    /// <inheritdoc cref="WriteWinRTMetadataTypeNameAttribute(IndentedTextWriter, ProjectionEmitContext, TypeDefinition)"/>
    /// <returns>A callback emitting the attribute body (no trailing newline) so it can be interpolated into a multiline template.</returns>
    public static WriteWinRTMetadataTypeNameAttributeCallback WriteWinRTMetadataTypeNameAttribute(ProjectionEmitContext context, TypeDefinition type)
    {
        return new(context, type);
    }

    /// <summary>
    /// Writes just the attribute body (no trailing newline) for <see cref="WriteWinRTMetadataTypeNameAttribute(IndentedTextWriter, ProjectionEmitContext, TypeDefinition)"/>.
    /// </summary>
    internal static void WriteWinRTMetadataTypeNameAttributeBody(IndentedTextWriter writer, ProjectionEmitContext context, TypeDefinition type)
    {
        WriteTypedefNameWithTypeParamsCallback typeName = TypedefNameWriter.WriteTypedefNameWithTypeParams(context, type, TypedefNameType.NonProjected, true);

        writer.Write($"""[WindowsRuntimeMetadataTypeName("{typeName}")]""");
    }

    /// <summary>
    /// Writes a <c>[WindowsRuntimeMappedType]</c> attribute pointing at the projected type.
    /// </summary>
    /// <param name="writer">The writer to emit to.</param>
    /// <param name="context">The active emit context.</param>
    /// <param name="type">The type definition.</param>
    public static void WriteWinRTMappedTypeAttribute(IndentedTextWriter writer, ProjectionEmitContext context, TypeDefinition type)
    {
        WriteWinRTMappedTypeAttributeBody(writer, context, type);
        writer.WriteLine();
    }

    /// <inheritdoc cref="WriteWinRTMappedTypeAttribute(IndentedTextWriter, ProjectionEmitContext, TypeDefinition)"/>
    /// <returns>A callback emitting the attribute body (no trailing newline) so it can be interpolated into a multiline template.</returns>
    public static WriteWinRTMappedTypeAttributeCallback WriteWinRTMappedTypeAttribute(ProjectionEmitContext context, TypeDefinition type)
    {
        return new(context, type);
    }

    /// <summary>
    /// Writes just the attribute body (no trailing newline) for <see cref="WriteWinRTMappedTypeAttribute(IndentedTextWriter, ProjectionEmitContext, TypeDefinition)"/>.
    /// </summary>
    internal static void WriteWinRTMappedTypeAttributeBody(IndentedTextWriter writer, ProjectionEmitContext context, TypeDefinition type)
    {
        WriteTypedefNameWithTypeParamsCallback typeName = TypedefNameWriter.WriteTypedefNameWithTypeParams(context, type, TypedefNameType.Projected, true);

        writer.Write($"[WindowsRuntimeMappedType(typeof({typeName}))]");
    }

    /// <summary>
    /// Writes a <c>[WindowsRuntimeClassName("Windows.Foundation.IReference`1&lt;NS.Name&gt;")]</c> attribute for a value type.
    /// Skipped entirely in reference-projection mode.
    /// </summary>
    /// <param name="writer">The writer to emit to.</param>
    /// <param name="context">The active emit context.</param>
    /// <param name="type">The value type definition.</param>
    public static void WriteValueTypeWinRTClassNameAttribute(IndentedTextWriter writer, ProjectionEmitContext context, TypeDefinition type)
    {
        int before = writer.Length;
        WriteValueTypeWinRTClassNameAttributeBody(writer, context, type);
        if (writer.Length > before)
        {
            writer.WriteLine();
        }
    }

    /// <inheritdoc cref="WriteValueTypeWinRTClassNameAttribute(IndentedTextWriter, ProjectionEmitContext, TypeDefinition)"/>
    /// <returns>A callback emitting the attribute body (no trailing newline) so it can be interpolated into a multiline template. Emits nothing in reference-projection mode (which combined with the writer's blank-line suppression collapses the would-be template line).</returns>
    public static WriteValueTypeWinRTClassNameAttributeCallback WriteValueTypeWinRTClassNameAttribute(ProjectionEmitContext context, TypeDefinition type)
    {
        return new(context, type);
    }

    /// <summary>
    /// Writes just the attribute body (no trailing newline) for <see cref="WriteValueTypeWinRTClassNameAttribute(IndentedTextWriter, ProjectionEmitContext, TypeDefinition)"/>.
    /// In reference-projection mode this emits nothing.
    /// </summary>
    internal static void WriteValueTypeWinRTClassNameAttributeBody(IndentedTextWriter writer, ProjectionEmitContext context, TypeDefinition type)
    {
        if (context.Settings.ReferenceProjection)
        {
            return;
        }

        (string ns, string name) = type.Names();
        writer.Write($"[WindowsRuntimeClassName(\"Windows.Foundation.IReference`1<{ns}.{name}>\")]");
    }

    /// <summary>
    /// Writes a <c>[WindowsRuntimeReferenceType(typeof(NullableX))]</c> attribute on a reference type.
    /// Skipped entirely in reference-projection mode.
    /// </summary>
    /// <param name="writer">The writer to emit to.</param>
    /// <param name="context">The active emit context.</param>
    /// <param name="type">The reference type definition.</param>
    public static void WriteWinRTReferenceTypeAttribute(IndentedTextWriter writer, ProjectionEmitContext context, TypeDefinition type)
    {
        int before = writer.Length;
        WriteWinRTReferenceTypeAttributeBody(writer, context, type);
        if (writer.Length > before)
        {
            writer.WriteLine();
        }
    }

    /// <inheritdoc cref="WriteWinRTReferenceTypeAttribute(IndentedTextWriter, ProjectionEmitContext, TypeDefinition)"/>
    /// <returns>A callback emitting the attribute body (no trailing newline) so it can be interpolated into a multiline template. Emits nothing in reference-projection mode.</returns>
    public static WriteWinRTReferenceTypeAttributeCallback WriteWinRTReferenceTypeAttribute(ProjectionEmitContext context, TypeDefinition type)
    {
        return new(context, type);
    }

    /// <summary>
    /// Writes just the attribute body (no trailing newline) for <see cref="WriteWinRTReferenceTypeAttribute(IndentedTextWriter, ProjectionEmitContext, TypeDefinition)"/>.
    /// In reference-projection mode this emits nothing.
    /// </summary>
    internal static void WriteWinRTReferenceTypeAttributeBody(IndentedTextWriter writer, ProjectionEmitContext context, TypeDefinition type)
    {
        if (context.Settings.ReferenceProjection)
        {
            return;
        }

        WriteTypedefNameWithTypeParamsCallback typeName = TypedefNameWriter.WriteTypedefNameWithTypeParams(context, type, TypedefNameType.Projected, false);

        writer.Write($"[WindowsRuntimeReferenceType(typeof({typeName}?))]");
    }

    /// <summary>
    /// Writes the <c>[ABI.NS.NameComWrappersMarshaller]</c> attribute. Skipped entirely in reference-projection mode.
    /// </summary>
    /// <param name="writer">The writer to emit to.</param>
    /// <param name="context">The active emit context.</param>
    /// <param name="type">The type definition.</param>
    public static void WriteComWrapperMarshallerAttribute(IndentedTextWriter writer, ProjectionEmitContext context, TypeDefinition type)
    {
        int before = writer.Length;
        WriteComWrapperMarshallerAttributeBody(writer, context, type);
        if (writer.Length > before)
        {
            writer.WriteLine();
        }
    }

    /// <inheritdoc cref="WriteComWrapperMarshallerAttribute(IndentedTextWriter, ProjectionEmitContext, TypeDefinition)"/>
    /// <returns>A callback emitting the attribute body (no trailing newline) so it can be interpolated into a multiline template. Emits nothing in reference-projection mode.</returns>
    public static WriteComWrapperMarshallerAttributeCallback WriteComWrapperMarshallerAttribute(ProjectionEmitContext context, TypeDefinition type)
    {
        return new(context, type);
    }

    /// <summary>
    /// Writes just the attribute body (no trailing newline) for <see cref="WriteComWrapperMarshallerAttribute(IndentedTextWriter, ProjectionEmitContext, TypeDefinition)"/>.
    /// In reference-projection mode this emits nothing.
    /// </summary>
    internal static void WriteComWrapperMarshallerAttributeBody(IndentedTextWriter writer, ProjectionEmitContext context, TypeDefinition type)
    {
        if (context.Settings.ReferenceProjection)
        {
            return;
        }

        (string ns, string name) = type.Names();
        writer.Write($"[ABI.{ns}.{IdentifierEscaping.StripBackticks(name)}ComWrappersMarshaller]");
    }

    /// <summary>
    /// Writes the <c>[assembly: TypeMap&lt;WindowsRuntimeMetadataTypeMapGroup&gt;]</c> attribute
    /// for an authored / projected type.
    /// </summary>
    /// <param name="writer">The writer to emit to.</param>
    /// <param name="context">The active emit context.</param>
    /// <param name="type">The type definition.</param>
    public static void WriteWinRTWindowsMetadataTypeMapGroupAssemblyAttribute(IndentedTextWriter writer, ProjectionEmitContext context, TypeDefinition type)
    {
        // Skip exclusive interfaces and projection-internal interfaces.
        if (type.IsInterface &&
            (type.IsExclusiveTo || type.IsProjectionInternal))
        {
            return;
        }

        // Capture the projected type name as a string by writing into a scratch writer at indent 0.
        string projectionName = TypedefNameWriter.WriteTypedefNameWithTypeParams(context, type, TypedefNameType.NonProjected, true).Format();

        // The 'target:' slot is the ABI typedef name in component mode, otherwise the projected name.
        string target = (context.Settings.Component
            ? TypedefNameWriter.WriteTypedefNameWithTypeParams(context, type, TypedefNameType.ABI, true)
            : TypedefNameWriter.WriteTypedefNameWithTypeParams(context, type, TypedefNameType.NonProjected, true)).Format();

        WriteTypeMapAttribute(writer, "WindowsRuntimeMetadataTypeMapGroup", $"\"{projectionName}\"", $"typeof({target})", $"typeof({projectionName})");

        if (context.Settings.Component)
        {
            WriteTypeMapAssociation(writer, "WindowsRuntimeMetadataTypeMapGroup", $"typeof({projectionName})", $"typeof({target})");
            writer.WriteLine();
        }
    }

    /// <summary>
    /// Writes the <c>[assembly: TypeMap&lt;WindowsRuntimeComWrappersTypeMapGroup&gt;]</c> attribute
    /// for the type's ComWrappers marshalling registration.
    /// </summary>
    /// <param name="writer">The writer to emit to.</param>
    /// <param name="context">The active emit context.</param>
    /// <param name="type">The type definition.</param>
    /// <param name="isValueType">When <see langword="true"/>, wraps the projected type in <c>Windows.Foundation.IReference`1&lt;...&gt;</c>.</param>
    public static void WriteWinRTComWrappersTypeMapGroupAssemblyAttribute(IndentedTextWriter writer, ProjectionEmitContext context, TypeDefinition type, bool isValueType)
    {
        string projectionName = TypedefNameWriter.WriteTypedefNameWithTypeParams(context, type, TypedefNameType.NonProjected, true).Format();

        // The 'value:' slot is wrapped in 'Windows.Foundation.IReference`1<...>' for value types.
        string value = isValueType ? $"Windows.Foundation.IReference`1<{projectionName}>" : projectionName;

        // The 'target:' slot is the ABI typedef name in component mode, otherwise the projected name.
        string target = (context.Settings.Component
            ? TypedefNameWriter.WriteTypedefNameWithTypeParams(context, type, TypedefNameType.ABI, true)
            : TypedefNameWriter.WriteTypedefNameWithTypeParams(context, type, TypedefNameType.NonProjected, true)).Format();

        WriteTypeMapAttribute(writer, "WindowsRuntimeComWrappersTypeMapGroup", $"\"{value}\"", $"typeof({target})", $"typeof({projectionName})");

        // For non-interface, non-struct authored types, emit proxy association.
        TypeKind cat = TypeKindResolver.Resolve(type);

        if (cat is not (TypeKind.Interface or TypeKind.Struct) && context.Settings.Component)
        {
            WriteTypeMapAssociation(writer, "WindowsRuntimeComWrappersTypeMapGroup", $"typeof({projectionName})", $"typeof({target})");
            writer.WriteLine();
        }
    }

    /// <summary>
    /// Writes the <c>[assembly: TypeMapAssociation&lt;DynamicInterfaceCastableImplementationTypeMapGroup&gt;]</c>
    /// attribute for an interface's dynamic-interface-castable implementation registration.
    /// </summary>
    /// <param name="writer">The writer to emit to.</param>
    /// <param name="context">The active emit context.</param>
    /// <param name="type">The interface type definition.</param>
    public static void WriteWinRTIdicTypeMapGroupAssemblyAttribute(IndentedTextWriter writer, ProjectionEmitContext context, TypeDefinition type)
    {
        // Generic interfaces are handled elsewhere.
        if (type.GenericParameters.Count != 0)
        {
            return;
        }

        // Skip exclusive interfaces (unless idic_exclusiveto), and projection-internal types.
        if ((type.IsExclusiveTo && !context.Settings.IdicExclusiveTo) ||
            type.IsProjectionInternal)
        {
            return;
        }

        string source = TypedefNameWriter.WriteTypedefNameWithTypeParams(context, type, TypedefNameType.Projected, true).Format();
        string proxy = TypedefNameWriter.WriteTypedefNameWithTypeParams(context, type, TypedefNameType.ABI, true).Format();

        WriteTypeMapAssociation(writer, "DynamicInterfaceCastableImplementationTypeMapGroup", $"typeof({source})", $"typeof({proxy})");
        writer.WriteLine();
    }

    /// <summary>
    /// Emits a single <c>[assembly: TypeMap&lt;<paramref name="group"/>&gt;(value, target, trimTarget)]</c> line
    /// preceded by a blank line. Used by the three <c>Write*TypeMapGroupAssemblyAttribute</c> helpers.
    /// </summary>
    private static void WriteTypeMapAttribute(IndentedTextWriter writer, string group, string value, string target, string trimTarget)
    {
        writer.WriteLine();
        writer.WriteLine(isMultiline: true, $$"""
            [assembly: TypeMap<{{group}}>(
                value: {{value}},
                target: {{target}},
                trimTarget: {{trimTarget}})]
            """);
    }

    /// <summary>
    /// Emits a single <c>[assembly: TypeMapAssociation&lt;<paramref name="group"/>&gt;(source, proxy)]</c> line
    /// preceded by a blank line. Used by the three <c>Write*TypeMapGroupAssemblyAttribute</c> helpers.
    /// </summary>
    private static void WriteTypeMapAssociation(IndentedTextWriter writer, string group, string source, string proxy)
    {
        writer.WriteLine();
        writer.WriteLine(isMultiline: true, $$"""
            [assembly: TypeMapAssociation<{{group}}>(
                source: {{source}},
                proxy: {{proxy}})]
            """);
    }

    /// <summary>
    /// Adds an entry to the default-interface map for a class type.
    /// </summary>
    public static void AddDefaultInterfaceEntry(ProjectionEmitContext context, TypeDefinition type, System.Collections.Concurrent.ConcurrentDictionary<string, string> entries)
    {
        if (context.Settings.ReferenceProjection)
        {
            return;
        }

        ITypeDefOrRef? defaultIface = type.GetDefaultInterface();

        if (defaultIface is null)
        {
            return;
        }

        (string typeNs, string typeName) = type.Names();
        string className = TypedefNameWriter.BuildGlobalQualifiedName(typeNs, typeName);

        // Resolve TypeReference -> TypeDefinition so WriteTypeName goes through the Definition
        // branch which knows about authored-type CCW namespacing (ABI.Impl. prefix).
        ITypeDefOrRef capturedIface = defaultIface;

        if (capturedIface is not TypeDefinition && capturedIface is not TypeSpecification && context.Cache is not null)
        {
            TypeDefinition? resolved = capturedIface.TryResolve(context.Cache.RuntimeContext);

            if (resolved is not null)
            {
                capturedIface = resolved;
            }
        }

        // Build the interface display name via TypeSemantics so generic instantiations
        // (e.g. IDictionary<string, BasicStruct>), TypeRefs and TypeDefs are all handled correctly.
        string interfaceName = TypedefNameWriter.WriteTypeName(context, TypeSemanticsFactory.GetFromTypeDefOrRef(capturedIface), TypedefNameType.CCW, true).Format();

        _ = entries.TryAdd(className, interfaceName);
    }

    /// <summary>
    /// Adds entries for [ExclusiveTo] interfaces of the class type.
    /// </summary>
    public static void AddExclusiveToInterfaceEntries(ProjectionEmitContext context, TypeDefinition type, System.Collections.Concurrent.ConcurrentBag<KeyValuePair<string, string>> entries)
    {
        if (!context.Settings.Component || context.Settings.ReferenceProjection)
        {
            return;
        }

        (string typeNs, string typeName) = type.Names();
        string className = TypedefNameWriter.BuildGlobalQualifiedName(typeNs, typeName);

        foreach (InterfaceImplementation impl in type.Interfaces)
        {
            if (impl.Interface is null)
            {
                continue;
            }

            // Resolve the interface to a TypeDefinition for the [ExclusiveTo] check.
            TypeDefinition? ifaceDef = impl.Interface as TypeDefinition;

            if (ifaceDef is null && context.Cache is not null)
            {
                ifaceDef = impl.Interface.TryResolve(context.Cache.RuntimeContext);
            }

            if (ifaceDef is null && impl.Interface is TypeSpecification spec
                && spec.Signature is GenericInstanceTypeSignature gi)
            {
                ifaceDef = gi.GenericType as TypeDefinition;

                if (ifaceDef is null && context.Cache is not null)
                {
                    ifaceDef = gi.GenericType.TryResolve(context.Cache.RuntimeContext);
                }
            }

            if (ifaceDef is null)
            {
                continue;
            }

            if (ifaceDef.IsExclusiveTo)
            {
                // Resolve TypeReference -> TypeDefinition so WriteTypeName goes through the
                // Definition branch which knows about authored-type CCW namespacing.
                ITypeDefOrRef capturedIface = impl.Interface;

                if (capturedIface is not TypeDefinition && capturedIface is not TypeSpecification && context.Cache is not null)
                {
                    TypeDefinition? resolved = capturedIface.TryResolve(context.Cache.RuntimeContext);

                    if (resolved is not null)
                    {
                        capturedIface = resolved;
                    }
                }

                string interfaceName = TypedefNameWriter.WriteTypeName(context, TypeSemanticsFactory.GetFromTypeDefOrRef(capturedIface), TypedefNameType.CCW, true).Format();
                entries.Add(new KeyValuePair<string, string>(className, interfaceName));
            }
        }
    }

    /// <summary>
    /// Writes the generated WindowsRuntimeDefaultInterfaces.cs file.
    /// </summary>
    public static void WriteDefaultInterfacesClass(Settings settings, IReadOnlyList<KeyValuePair<string, string>> sortedEntries)
    {
        WriteInterfaceMapClass(settings, sortedEntries, "WindowsRuntimeDefaultInterface", "WindowsRuntimeDefaultInterfaces", "WindowsRuntimeDefaultInterfaces.cs");
    }

    /// <summary>
    /// Writes the generated WindowsRuntimeExclusiveToInterfaces.cs file.
    /// </summary>
    public static void WriteExclusiveToInterfacesClass(Settings settings, IReadOnlyList<KeyValuePair<string, string>> sortedEntries)
    {
        WriteInterfaceMapClass(settings, sortedEntries, "WindowsRuntimeExclusiveToInterface", "WindowsRuntimeExclusiveToInterfaces", "WindowsRuntimeExclusiveToInterfaces.cs");
    }

    /// <summary>
    /// Shared template for emitting an <c>ABI</c> namespace-level static class decorated with one
    /// <paramref name="attributeName"/> per entry from <paramref name="sortedEntries"/> (mapping
    /// projected type names to interface or proxy type names). Used by both
    /// <see cref="WriteDefaultInterfacesClass"/> and <see cref="WriteExclusiveToInterfacesClass"/>.
    /// </summary>
    private static void WriteInterfaceMapClass(
        Settings settings,
        IReadOnlyList<KeyValuePair<string, string>> sortedEntries,
        string attributeName,
        string className,
        string fileName)
    {
        if (sortedEntries.Count == 0)
        {
            return;
        }

        using IndentedTextWriterOwner wOwner = IndentedTextWriterPool.GetOrCreate();
        IndentedTextWriter w = wOwner.Writer;
        WriteFileHeader(w);
        w.WriteLine("using System;");
        w.WriteLine("using WindowsRuntime;");
        w.WriteLine();
        w.WriteLine("#pragma warning disable CSWINRT3001");
        w.WriteLine();
        w.WriteLine("namespace ABI");
        using (w.WriteBlock())
        {
            foreach (KeyValuePair<string, string> kv in sortedEntries)
            {
                w.WriteLine($"[{attributeName}(typeof({kv.Key}), typeof({kv.Value}))]");
            }

            w.WriteLine($"internal static class {className};");
        }

        w.FlushToFile(Path.Combine(settings.OutputFolder, fileName));
    }
}
