// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Collections.Generic;
using System.IO;
using AsmResolver.DotNet;
using AsmResolver.DotNet.Signatures;
using WindowsRuntime.ProjectionWriter.Builders;
using WindowsRuntime.ProjectionWriter.Generation;
using WindowsRuntime.ProjectionWriter.Helpers;
using WindowsRuntime.ProjectionWriter.Metadata;
using WindowsRuntime.ProjectionWriter.Writers;

namespace WindowsRuntime.ProjectionWriter.Factories;

/// <summary>
/// Helper writers for assembly attributes, metadata attributes, file headers, and
/// other infrastructure that runs at the top or bottom of every emitted projection
/// file.
/// </summary>
internal static class MetadataAttributeFactory
{
    /// <summary>
    /// Writes <c>#pragma warning disable IL2026</c>.
    /// </summary>
    /// <param name="writer">The writer to emit to.</param>
    public static void WritePragmaDisableIL2026(IndentedTextWriter writer)
    {
        writer.WriteLine();
        writer.WriteLine("#pragma warning disable IL2026");
    }

    /// <summary>
    /// Writes <c>#pragma warning restore IL2026</c>.
    /// </summary>
    /// <param name="writer">The writer to emit to.</param>
    public static void WritePragmaRestoreIL2026(IndentedTextWriter writer)
    {
        writer.WriteLine();
        writer.WriteLine("#pragma warning restore IL2026");
    }

    /// <summary>
    /// Returns the version string embedded in the banner comment of generated files.
    /// MSBuild and defaults to <c>0.0.0-private.0</c>).
    /// We read the writer assembly's <see cref="System.Reflection.AssemblyInformationalVersionAttribute"/>
    /// (set via <c>$(InformationalVersion)</c>) and strip any SourceLink commit-sha suffix
    /// after a '+' so the banner is reproducible across rebuilds of the same source.
    /// </summary>
    internal static string GetVersionString()
    {
        System.Reflection.Assembly asm = typeof(ProjectionFileBuilder).Assembly;
        System.Reflection.AssemblyInformationalVersionAttribute? attr =
            (System.Reflection.AssemblyInformationalVersionAttribute?)System.Attribute.GetCustomAttribute(
                asm, typeof(System.Reflection.AssemblyInformationalVersionAttribute));
        string version = attr?.InformationalVersion ?? "0.0.0-private.0";
        int plus = version.IndexOf('+');
        return plus >= 0 ? version[..plus] : version;
    }
    /// <summary>
    /// Writes the standard auto-generated banner comment (no <c>using</c> imports, no pragmas).
    /// Used for the leaner <c>WinRT_Module.cs</c> / <c>GeneratedInterfaceIIDs.cs</c> /
    /// <c>Resources/Base/*.cs</c> output prelude. Distinct from
    /// <see cref="ProjectionWriterExtensions.WriteFileHeader"/>, which also emits the canonical
    /// <c>using</c> imports + suppression pragmas.
    /// </summary>
    /// <param name="writer">The writer to emit the banner to.</param>
    public static void WriteFileHeader(IndentedTextWriter writer)
    {
        writer.Write($$"""
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This file was generated by cswinrt.exe version {{GetVersionString()}}
            //
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------
            """, isMultiline: true);
    }

    /// <summary>
    /// Writes a <c>[WindowsRuntimeMetadata]</c> attribute decorating <paramref name="type"/> with its source <c>.winmd</c> module name.
    /// </summary>
    /// <param name="writer">The writer to emit to.</param>
    /// <param name="type">The type definition.</param>
    /// <param name="cache">The metadata cache used to resolve the source module path.</param>
    public static void WriteWinRTMetadataAttribute(IndentedTextWriter writer, TypeDefinition type, MetadataCache cache)
    {
        string path = cache.GetSourcePath(type);
        string stem = string.IsNullOrEmpty(path) ? string.Empty : Path.GetFileNameWithoutExtension(path);
        writer.WriteLine($"[WindowsRuntimeMetadata(\"{stem}\")]");
    }

    /// <summary>
    /// Writes a <c>[WindowsRuntimeMetadataTypeName]</c> attribute carrying the WinRT type name string.
    /// </summary>
    /// <param name="writer">The writer to emit to.</param>
    /// <param name="context">The active emit context.</param>
    /// <param name="type">The type definition.</param>
    public static void WriteWinRTMetadataTypeNameAttribute(IndentedTextWriter writer, ProjectionEmitContext context, TypeDefinition type)
    {
        writer.Write("[WindowsRuntimeMetadataTypeName(\"");
        TypedefNameWriter.WriteTypedefName(writer, context, type, TypedefNameType.NonProjected, true);
        TypedefNameWriter.WriteTypeParams(writer, type);
        writer.WriteLine("\")]");
    }

    /// <summary>
    /// Writes a <c>[WindowsRuntimeMappedType]</c> attribute pointing at the projected type.
    /// </summary>
    /// <param name="writer">The writer to emit to.</param>
    /// <param name="context">The active emit context.</param>
    /// <param name="type">The type definition.</param>
    public static void WriteWinRTMappedTypeAttribute(IndentedTextWriter writer, ProjectionEmitContext context, TypeDefinition type)
    {
        writer.Write("[WindowsRuntimeMappedType(typeof(");
        TypedefNameWriter.WriteTypedefName(writer, context, type, TypedefNameType.Projected, true);
        TypedefNameWriter.WriteTypeParams(writer, type);
        writer.WriteLine("))]");
    }

    /// <summary>
    /// Writes a <c>[WindowsRuntimeClassName("Windows.Foundation.IReference`1&lt;NS.Name&gt;")]</c> attribute for a value type.
    /// </summary>
    /// <param name="writer">The writer to emit to.</param>
    /// <param name="context">The active emit context.</param>
    /// <param name="type">The value type definition.</param>
    public static void WriteValueTypeWinRTClassNameAttribute(IndentedTextWriter writer, ProjectionEmitContext context, TypeDefinition type)
    {
        if (context.Settings.ReferenceProjection) { return; }
        (string ns, string name) = type.Names();
        writer.WriteLine($"[WindowsRuntimeClassName(\"Windows.Foundation.IReference`1<{ns}.{name}>\")]");
    }

    /// <summary>
    /// Writes a <c>[WindowsRuntimeReferenceType(typeof(NullableX))]</c> attribute on a reference type.
    /// </summary>
    /// <param name="writer">The writer to emit to.</param>
    /// <param name="context">The active emit context.</param>
    /// <param name="type">The reference type definition.</param>
    public static void WriteWinRTReferenceTypeAttribute(IndentedTextWriter writer, ProjectionEmitContext context, TypeDefinition type)
    {
        if (context.Settings.ReferenceProjection) { return; }
        writer.Write("[WindowsRuntimeReferenceType(typeof(");
        TypedefNameWriter.WriteTypedefName(writer, context, type, TypedefNameType.Projected, false);
        TypedefNameWriter.WriteTypeParams(writer, type);
        writer.WriteLine("?))]");
    }

    /// <summary>
    /// Writes the <c>[ABI.NS.NameComWrappersMarshaller]</c> attribute.
    /// </summary>
    /// <param name="writer">The writer to emit to.</param>
    /// <param name="context">The active emit context.</param>
    /// <param name="type">The type definition.</param>
    public static void WriteComWrapperMarshallerAttribute(IndentedTextWriter writer, ProjectionEmitContext context, TypeDefinition type)
    {
        if (context.Settings.ReferenceProjection) { return; }
        (string ns, string name) = type.Names();
        writer.WriteLine($"[ABI.{ns}.{IdentifierEscaping.StripBackticks(name)}ComWrappersMarshaller]");
    }

    /// <summary>
    /// Writes the <c>[assembly: TypeMap&lt;WindowsRuntimeMetadataTypeMapGroup&gt;]</c> attribute
    /// for an authored / projected type.
    /// </summary>
    /// <param name="writer">The writer to emit to.</param>
    /// <param name="context">The active emit context.</param>
    /// <param name="type">The type definition.</param>
    public static void WriteWinRTWindowsMetadataTypeMapGroupAssemblyAttribute(IndentedTextWriter writer, ProjectionEmitContext context, TypeDefinition type)
    {
        // Skip exclusive interfaces and projection-internal interfaces.
        if (TypeCategorization.GetCategory(type) == TypeCategory.Interface &&
            (TypeCategorization.IsExclusiveTo(type) || TypeCategorization.IsProjectionInternal(type)))
        {
            return;
        }

        // Capture the projected type name as a string by writing into a scratch writer at indent 0.
        string projectionName = TypedefNameWriter.WriteTypedefNameWithTypeParams(context, type, TypedefNameType.NonProjected, true);

        writer.WriteLine();
        writer.Write($$"""
            [assembly: TypeMap<WindowsRuntimeMetadataTypeMapGroup>(
                value: "{{projectionName}}",
                target: typeof(
            """, isMultiline: true);
        if (context.Settings.Component)
        {
            TypedefNameWriter.WriteTypedefName(writer, context, type, TypedefNameType.ABI, true);
            TypedefNameWriter.WriteTypeParams(writer, type);
        }
        else
        {
            writer.Write(projectionName);
        }
        writer.Write($$"""
            ),
                trimTarget: typeof({{projectionName}}))]
            """, isMultiline: true);

        if (context.Settings.Component)
        {
            writer.WriteLine();
            writer.Write($$"""
                [assembly: TypeMapAssociation<WindowsRuntimeMetadataTypeMapGroup>(
                    source: typeof({{projectionName}}),
                    proxy: typeof(
                """, isMultiline: true);
            TypedefNameWriter.WriteTypedefName(writer, context, type, TypedefNameType.ABI, true);
            TypedefNameWriter.WriteTypeParams(writer, type);
            writer.WriteLine("))]");
            writer.WriteLine();
        }
    }

    /// <summary>
    /// Writes the <c>[assembly: TypeMap&lt;WindowsRuntimeComWrappersTypeMapGroup&gt;]</c> attribute
    /// for the type's ComWrappers marshalling registration.
    /// </summary>
    /// <param name="writer">The writer to emit to.</param>
    /// <param name="context">The active emit context.</param>
    /// <param name="type">The type definition.</param>
    /// <param name="isValueType">When <see langword="true"/>, wraps the projected type in <c>Windows.Foundation.IReference`1&lt;...&gt;</c>.</param>
    public static void WriteWinRTComWrappersTypeMapGroupAssemblyAttribute(IndentedTextWriter writer, ProjectionEmitContext context, TypeDefinition type, bool isValueType)
    {
        string projectionName = TypedefNameWriter.WriteTypedefNameWithTypeParams(context, type, TypedefNameType.NonProjected, true);

        writer.WriteLine();
        writer.Write("""
            [assembly: TypeMap<WindowsRuntimeComWrappersTypeMapGroup>(
                value: "
            """, isMultiline: true);
        if (isValueType)
        {
            writer.Write($"Windows.Foundation.IReference`1<{projectionName}>");
        }
        else
        {
            writer.Write(projectionName);
        }
        writer.Write("""
            ",
                target: typeof(
            """, isMultiline: true);
        if (context.Settings.Component)
        {
            TypedefNameWriter.WriteTypedefName(writer, context, type, TypedefNameType.ABI, true);
            TypedefNameWriter.WriteTypeParams(writer, type);
        }
        else
        {
            writer.Write(projectionName);
        }
        writer.Write($$"""
            ),
                trimTarget: typeof({{projectionName}}))]
            """, isMultiline: true);

        // For non-interface, non-struct authored types, emit proxy association.
        TypeCategory cat = TypeCategorization.GetCategory(type);
        if (cat is not (TypeCategory.Interface or TypeCategory.Struct) && context.Settings.Component)
        {
            writer.WriteLine();
            writer.Write($$"""
                [assembly: TypeMapAssociation<WindowsRuntimeComWrappersTypeMapGroup>(
                    source: typeof({{projectionName}}),
                    proxy: typeof(
                """, isMultiline: true);
            TypedefNameWriter.WriteTypedefName(writer, context, type, TypedefNameType.ABI, true);
            TypedefNameWriter.WriteTypeParams(writer, type);
            writer.WriteLine("))]");
            writer.WriteLine();
        }
    }

    /// <summary>
    /// Writes the <c>[assembly: TypeMapAssociation&lt;DynamicInterfaceCastableImplementationTypeMapGroup&gt;]</c>
    /// attribute for an interface's dynamic-interface-castable implementation registration.
    /// </summary>
    /// <param name="writer">The writer to emit to.</param>
    /// <param name="context">The active emit context.</param>
    /// <param name="type">The interface type definition.</param>
    public static void WriteWinRTIdicTypeMapGroupAssemblyAttribute(IndentedTextWriter writer, ProjectionEmitContext context, TypeDefinition type)
    {
        // Generic interfaces are handled elsewhere.
        if (type.GenericParameters.Count != 0) { return; }
        // Skip exclusive interfaces (unless idic_exclusiveto), and projection-internal types.
        if ((TypeCategorization.IsExclusiveTo(type) && !context.Settings.IdicExclusiveTo) ||
            TypeCategorization.IsProjectionInternal(type))
        {
            return;
        }

        writer.WriteLine();
        writer.Write("""
            [assembly: TypeMapAssociation<DynamicInterfaceCastableImplementationTypeMapGroup>(
                source: typeof(
            """, isMultiline: true);
        TypedefNameWriter.WriteTypedefName(writer, context, type, TypedefNameType.Projected, true);
        TypedefNameWriter.WriteTypeParams(writer, type);
        writer.Write("""
            ),
                proxy: typeof(
            """, isMultiline: true);
        TypedefNameWriter.WriteTypedefName(writer, context, type, TypedefNameType.ABI, true);
        TypedefNameWriter.WriteTypeParams(writer, type);
        writer.WriteLine("))]");
        writer.WriteLine();
    }

    /// <summary>
    /// Adds an entry to the default-interface map for a class type.
    /// </summary>
    public static void AddDefaultInterfaceEntry(ProjectionEmitContext context, TypeDefinition type, System.Collections.Concurrent.ConcurrentDictionary<string, string> entries)
    {
        if (context.Settings.ReferenceProjection) { return; }
        ITypeDefOrRef? defaultIface = type.GetDefaultInterface();
        if (defaultIface is null) { return; }

        (string typeNs, string typeName) = type.Names();
        string className = $"global::{typeNs}.{IdentifierEscaping.StripBackticks(typeName)}";

        // Resolve TypeReference -> TypeDefinition so WriteTypeName goes through the Definition
        // branch which knows about authored-type CCW namespacing (ABI.Impl. prefix).
        ITypeDefOrRef capturedIface = defaultIface;
        if (capturedIface is not TypeDefinition && capturedIface is not TypeSpecification && context.Cache is not null)
        {
            TypeDefinition? resolved = capturedIface.TryResolve(context.Cache.RuntimeContext);
            if (resolved is not null) { capturedIface = resolved; }
        }

        // Build the interface display name via TypeSemantics so generic instantiations
        // (e.g. IDictionary<string, BasicStruct>), TypeRefs and TypeDefs are all handled correctly.
        string interfaceName = TypedefNameWriter.WriteTypeName(context, TypeSemanticsFactory.GetFromTypeDefOrRef(capturedIface), TypedefNameType.CCW, true);

        _ = entries.TryAdd(className, interfaceName);
    }
    /// <summary>
    /// Adds entries for [ExclusiveTo] interfaces of the class type.
    /// </summary>
    public static void AddExclusiveToInterfaceEntries(ProjectionEmitContext context, TypeDefinition type, System.Collections.Concurrent.ConcurrentBag<KeyValuePair<string, string>> entries)
    {
        if (!context.Settings.Component || context.Settings.ReferenceProjection) { return; }
        (string typeNs, string typeName) = type.Names();
        string className = $"global::{typeNs}.{IdentifierEscaping.StripBackticks(typeName)}";

        foreach (InterfaceImplementation impl in type.Interfaces)
        {
            if (impl.Interface is null) { continue; }

            // Resolve the interface to a TypeDefinition for the [ExclusiveTo] check.
            TypeDefinition? ifaceDef = impl.Interface as TypeDefinition;
            if (ifaceDef is null && context.Cache is not null)
            {
                ifaceDef = impl.Interface.TryResolve(context.Cache.RuntimeContext);
            }
            if (ifaceDef is null && impl.Interface is TypeSpecification spec
                && spec.Signature is GenericInstanceTypeSignature gi)
            {
                ifaceDef = gi.GenericType as TypeDefinition;
                if (ifaceDef is null && context.Cache is not null)
                {
                    ifaceDef = gi.GenericType.TryResolve(context.Cache.RuntimeContext);
                }
            }
            if (ifaceDef is null) { continue; }

            if (TypeCategorization.IsExclusiveTo(ifaceDef))
            {
                // Resolve TypeReference -> TypeDefinition so WriteTypeName goes through the
                // Definition branch which knows about authored-type CCW namespacing.
                ITypeDefOrRef capturedIface = impl.Interface;
                if (capturedIface is not TypeDefinition && capturedIface is not TypeSpecification && context.Cache is not null)
                {
                    TypeDefinition? resolved = capturedIface.TryResolve(context.Cache.RuntimeContext);
                    if (resolved is not null) { capturedIface = resolved; }
                }
                string interfaceName = TypedefNameWriter.WriteTypeName(context, TypeSemanticsFactory.GetFromTypeDefOrRef(capturedIface), TypedefNameType.CCW, true);
                entries.Add(new KeyValuePair<string, string>(className, interfaceName));
            }
        }
    }
    /// <summary>
    /// Writes the generated WindowsRuntimeDefaultInterfaces.cs file.
    /// </summary>
    public static void WriteDefaultInterfacesClass(Settings settings, IReadOnlyList<KeyValuePair<string, string>> sortedEntries)
    {
        if (sortedEntries.Count == 0) { return; }
        IndentedTextWriter w = IndentedTextWriterPool.GetOrCreate();
        WriteFileHeader(w);
        w.Write("""
            using System;
            using WindowsRuntime;
            
            #pragma warning disable CSWINRT3001
            
            namespace ABI
            {
            """, isMultiline: true);
        foreach (KeyValuePair<string, string> kv in sortedEntries)
        {
            w.WriteLine($"[WindowsRuntimeDefaultInterface(typeof({kv.Key}), typeof({kv.Value}))]");
        }
        w.Write("""
            internal static class WindowsRuntimeDefaultInterfaces;
            }
            """, isMultiline: true);
        w.FlushToFile(Path.Combine(settings.OutputFolder, "WindowsRuntimeDefaultInterfaces.cs"));
        IndentedTextWriterPool.Return(w);
    }

    /// <summary>
    /// Writes the generated WindowsRuntimeExclusiveToInterfaces.cs file.
    /// </summary>
    public static void WriteExclusiveToInterfacesClass(Settings settings, IReadOnlyList<KeyValuePair<string, string>> sortedEntries)
    {
        if (sortedEntries.Count == 0) { return; }
        IndentedTextWriter w = IndentedTextWriterPool.GetOrCreate();
        WriteFileHeader(w);
        w.Write("""
            using System;
            using WindowsRuntime;
            
            #pragma warning disable CSWINRT3001
            
            namespace ABI
            {
            """, isMultiline: true);
        foreach (KeyValuePair<string, string> kv in sortedEntries)
        {
            w.WriteLine($"[WindowsRuntimeExclusiveToInterface(typeof({kv.Key}), typeof({kv.Value}))]");
        }
        w.Write("""
            internal static class WindowsRuntimeExclusiveToInterfaces;
            }
            """, isMultiline: true);
        w.FlushToFile(Path.Combine(settings.OutputFolder, "WindowsRuntimeExclusiveToInterfaces.cs"));
        IndentedTextWriterPool.Return(w);
    }
}
