// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using Microsoft.CodeAnalysis;

#pragma warning disable CS1734

namespace WindowsRuntime.SourceGenerator;

/// <summary>
/// Extensions for <see cref="ISymbol"/>.
/// </summary>
internal static class ISymbolExtensions
{
    /// <param name="symbol">The input <see cref="ISymbol"/> instance.</param>
    extension(ISymbol symbol)
    {
        /// <summary>
        /// Gets the fully qualified name for a given symbol.
        /// </summary>
        /// <returns>The fully qualified name for <paramref name="symbol"/>.</returns>
        public string GetFullyQualifiedName()
        {
            return symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }

        /// <summary>
        /// Gets the fully qualified name for a given symbol, including nullability annotations
        /// </summary>
        /// <returns>The fully qualified name for <paramref name="symbol"/>.</returns>
        public string GetFullyQualifiedNameWithNullabilityAnnotations()
        {
            return symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.AddMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier));
        }

        /// <summary>
        /// Checks whether a type has an attribute with a specified type.
        /// </summary>
        /// <param name="typeSymbol">The <see cref="ITypeSymbol"/> instance for the attribute type to look for.</param>
        /// <returns>Whether or not <paramref name="symbol"/> has an attribute with the specified name.</returns>
        public bool HasAttributeWithType(ITypeSymbol typeSymbol)
        {
            return TryGetAttributeWithType(symbol, typeSymbol, out _);
        }

        /// <summary>
        /// Tries to get an attribute with the specified type.
        /// </summary>
        /// <param name="typeSymbol">The <see cref="ITypeSymbol"/> instance for the attribute type to look for.</param>
        /// <param name="attributeData">The resulting attribute, if it was found.</param>
        /// <returns>Whether or not <paramref name="symbol"/> has an attribute with the specified name.</returns>
        public bool TryGetAttributeWithType(ITypeSymbol typeSymbol, [NotNullWhen(true)] out AttributeData? attributeData)
        {
            foreach (AttributeData attribute in symbol.GetAttributes())
            {
                if (SymbolEqualityComparer.Default.Equals(attribute.AttributeClass, typeSymbol))
                {
                    attributeData = attribute;

                    return true;
                }
            }

            attributeData = null;

            return false;
        }

        /// <summary>
        /// Gets all attributes applied to a symbol with a specified type.
        /// </summary>
        /// <param name="typeSymbol">The <see cref="INamedTypeSymbol"/> instance for the attribute type to look for.</param>
        /// <returns>The sequence of attributes applied to <paramref name="symbol"/> with the specified type.</returns>
        public IEnumerable<AttributeData> GetAttributes(INamedTypeSymbol typeSymbol)
        {
            foreach (AttributeData attribute in symbol.GetAttributes())
            {
                if (SymbolEqualityComparer.Default.Equals(attribute.AttributeClass, typeSymbol))
                {
                    yield return attribute;
                }
            }
        }

        /// <summary>
        /// Checks whether a given symbol is accessible from the assembly of a given compilation (including eg. through nested types).
        /// </summary>
        /// <param name="compilation">The <see cref="Compilation"/> instance currently in use.</param>
        /// <returns>Whether <paramref name="symbol"/> is accessible from the assembly for <paramref name="compilation"/>.</returns>
        public bool IsAccessibleFromCompilationAssembly(Compilation compilation)
        {
            return compilation.IsSymbolAccessibleWithin(symbol, compilation.Assembly);
        }
    }

    /// <param name="symbols">The input sequence of <see cref="ISymbol"/> instances.</param>
    extension(IEnumerable<ISymbol> symbols)
    {
        /// <summary>
        /// Checks whether all symbols in the sequence are generated by a specific generator.
        /// </summary>
        /// <param name="generatedCodeAttributeType">The <see cref="INamedTypeSymbol"/> for <c>[GeneratedCode]</c>.</param>
        /// <param name="generatorName">The generator name to match against the first constructor argument of <c>[GeneratedCode]</c>.</param>
        /// <returns>Whether all symbols in <paramref name="symbols"/> have a <c>[GeneratedCode]</c> attribute matching <paramref name="generatorName"/>.</returns>
        public bool AreAllImplementedByGenerator(INamedTypeSymbol generatedCodeAttributeType, string generatorName)
        {
            bool hasAtLeastOneImplementedMember = false;

            foreach (ISymbol symbol in symbols)
            {
                hasAtLeastOneImplementedMember = true;

                ISymbol currentSymbol = symbol;

                // First, try to get the attribute directly on the symbol (this should work in most cases)
                if (!currentSymbol.TryGetAttributeWithType(generatedCodeAttributeType, out AttributeData? attributeData))
                {
                    // If the current symbol is some property accessor, move to the associated property instead.
                    // This is also needed because usually '[GeneratedCode]' would only be on the property.
                    if (currentSymbol is IMethodSymbol { AssociatedSymbol: { } associatedSymbol })
                    {
                        currentSymbol = associatedSymbol;
                    }

                    // Stop if the symbol doesn't have '[GeneratedCode]' on it. Note, we want to traverse the symbol
                    // hierarchy and find the attribute on the closest parent (so we can also handle e.g. accessors).
                    for (ISymbol? parentSymbol = currentSymbol; parentSymbol is not null; parentSymbol = parentSymbol.ContainingSymbol)
                    {
                        if (parentSymbol.TryGetAttributeWithType(generatedCodeAttributeType, out attributeData))
                        {
                            break;
                        }
                    }
                }

                // Check that the symbol was specifically generated by the target generator
                if (attributeData is not { ConstructorArguments: [{ Value: string name }, ..] } || name != generatorName)
                {
                    return false;
                }
            }

            // If the input set is empty, we want to return 'false' to indicate that there are no implemented members
            return hasAtLeastOneImplementedMember;
        }
    }
}