// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System;
#if WINDOWS_RUNTIME_REFERENCE_ASSEMBLY
using System.ComponentModel;
#endif
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace WindowsRuntime;

/// <summary>
/// The base class for all projected Windows Runtime types.
/// </summary>
/// <remarks>
/// This type should only be used as a base type by generated projected types.
/// </remarks>
public abstract partial class WindowsRuntimeObject :
    IDynamicInterfaceCastable,
    IUnmanagedVirtualMethodTableProvider,
    ICustomQueryInterface
{
#if WINDOWS_RUNTIME_REFERENCE_ASSEMBLY
    /// <summary>
    /// Creates a <see cref="WindowsRuntimeObject"/> instance.
    /// </summary>
    /// <remarks>
    /// Deriving from <see cref="WindowsRuntimeObject"/> is only supported for projected types generated by CsWinRT,
    /// and invoking this from a user-defined type will result in a <see cref="MissingMethodException"/> at runtime.
    /// </remarks>
    [Obsolete(WindowsRuntimeConstants.WindowsRuntimeObjectConstructorObsoleteMessage,
        DiagnosticId = WindowsRuntimeConstants.WindowsRuntimeObjectConstructorObsoleteDiagnosticId,
        UrlFormat = WindowsRuntimeConstants.CsWinRTDiagnosticsUrlFormat)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    protected WindowsRuntimeObject()
    {
        throw null;
    }
#endif

    /// <inheritdoc/>
    RuntimeTypeHandle IDynamicInterfaceCastable.GetInterfaceImplementation(RuntimeTypeHandle interfaceType)
    {
#if WINDOWS_RUNTIME_REFERENCE_ASSEMBLY
        throw null;
#elif WINDOWS_RUNTIME_IMPLEMENTATION_ASSEMBLY
        return GetInterfaceImplementation(interfaceType);
#endif
    }

    /// <inheritdoc/>
    bool IDynamicInterfaceCastable.IsInterfaceImplemented(RuntimeTypeHandle interfaceType, bool throwIfNotImplemented)
    {
#if WINDOWS_RUNTIME_REFERENCE_ASSEMBLY
        throw null;
#elif WINDOWS_RUNTIME_IMPLEMENTATION_ASSEMBLY
        return IsInterfaceImplemented(interfaceType, throwIfNotImplemented);
#endif
    }

    /// <inheritdoc/>
    VirtualMethodTableInfo IUnmanagedVirtualMethodTableProvider.GetVirtualMethodTableInfoForKey(Type type)
    {
#if WINDOWS_RUNTIME_REFERENCE_ASSEMBLY
        throw null;
#elif WINDOWS_RUNTIME_IMPLEMENTATION_ASSEMBLY
        return GetVirtualMethodTableInfoForKey(type);
#endif
    }

    /// <inheritdoc/>
    CustomQueryInterfaceResult ICustomQueryInterface.GetInterface(ref Guid iid, out nint ppv)
    {
#if WINDOWS_RUNTIME_REFERENCE_ASSEMBLY
        throw null;
#elif WINDOWS_RUNTIME_IMPLEMENTATION_ASSEMBLY
        return GetInterface(ref iid, out ppv);
#endif
    }
}
