// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace WindowsRuntime;

/// <summary>
/// A type containing constants for various scenarios related to Windows Runtime functionality and projections.
/// </summary>
internal static class WindowsRuntimeConstants
{
    /// <summary>
    /// A message for the parameterless <see cref="WindowsRuntimeObject"/> constructor.
    /// </summary>
    public const string WindowsRuntimeObjectConstructorObsoleteMessage =
        "This constructor is a private implementation detail, and it must never be used. Deriving from 'WindowsRuntimeObject' is only " +
        "supported for projected types generated by CsWinRT (produced by 'cswinrtprojectiongen.exe' and 'cswinrtprojectionrefgen.exe'), " +
        "and it is not supported for user-defined types. This constructor is not present in the actual implementation assembly. " +
        "Deriving from 'WindowsRuntimeObject' in user code will result in a 'MissingMethodException' being thrown at runtime.";

    /// <summary>
    /// The diagnostic id for the parameterless <see cref="WindowsRuntimeObject"/> constructor.
    /// </summary>
    public const string WindowsRuntimeObjectConstructorObsoleteDiagnosticId = "CSWINRT3001";

    /// <summary>
    /// The URL format for all custom diagnostics for CsWinRT.
    /// </summary>
    /// <remarks>
    /// This URL format assumes it will receive the diagnostic id as a parameter.
    /// </remarks>
    public const string CsWinRTDiagnosticsUrlFormat = "https://aka.ms/cswinrt/errors/{0}";
}
