// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using WindowsRuntime.ProjectionWriter.Factories;
using WindowsRuntime.ProjectionWriter.Generation;
using WindowsRuntime.ProjectionWriter.Writers;

namespace WindowsRuntime.ProjectionWriter;

/// <summary>
/// WinRT-projection-specific emission helpers for <see cref="IndentedTextWriter"/>: file header,
/// projected/ABI namespace blocks, and pragma sections.
/// </summary>
internal static class ProjectionWriterExtensions
{
    extension(IndentedTextWriter writer)
    {
        /// <summary>
        /// Writes the standard auto-generated file header (the <c>cswinrt.exe</c> banner +
        /// canonical <c>using</c> imports + suppression pragmas) at the top of every emitted
        /// <c>.cs</c> file.
        /// </summary>
        /// <param name="context">The active emit context (currently unused, but reserved for future per-namespace customization).</param>
        public void WriteFileHeader(ProjectionEmitContext context)
        {
            writer.WriteLine($$"""
                //------------------------------------------------------------------------------
                // <auto-generated>
                //     This file was generated by cswinrt.exe version {{MetadataAttributeFactory.GetVersionString()}}
                //
                //     Changes to this file may cause incorrect behavior and will be lost if
                //     the code is regenerated.
                // </auto-generated>
                //------------------------------------------------------------------------------
                
                using System;
                using System.Collections;
                using System.Collections.Generic;
                using System.Collections.ObjectModel;
                using System.ComponentModel;
                using System.Diagnostics;
                using System.Diagnostics.CodeAnalysis;
                using System.Runtime.CompilerServices;
                using System.Runtime.InteropServices;
                using Windows.Foundation;
                using WindowsRuntime;
                using WindowsRuntime.InteropServices;
                using WindowsRuntime.InteropServices.Marshalling;
                using static System.Runtime.InteropServices.ComWrappers;
                
                #pragma warning disable CS0169 // "The field '...' is never used"
                #pragma warning disable CS0649 // "Field '...' is never assigned to"
                #pragma warning disable CA2207, CA1063, CA1033, CA1001, CA2213
                #pragma warning disable CSWINRT3001 // "Type or member '...' is a private implementation detail"
                #pragma warning disable CS8500 // This takes the address of, gets the size of, or declares a pointer to a managed type
                
                """, isMultiline: true);
        }

        /// <summary>
        /// Writes the opening <c>namespace ...</c> block for the projected namespace (with the
        /// <c>ABI.Impl.</c> prefix when emitting a Windows Runtime component projection).
        /// </summary>
        /// <param name="context">The active emit context (provides the namespace + component flag).</param>
        public void WriteBeginProjectedNamespace(ProjectionEmitContext context)
        {
            string nsPrefix = context.Settings.Component ? "ABI.Impl." : string.Empty;
            writer.WriteLine();
            writer.Write($$"""
                namespace {{nsPrefix}}{{context.CurrentNamespace}}
                {
                """, isMultiline: true);
            writer.IncreaseIndent();
        }

        /// <summary>
        /// Writes the closing <c>}</c> for the projected namespace.
        /// </summary>
        public void WriteEndProjectedNamespace()
        {
            writer.DecreaseIndent();
            writer.WriteLine("}");
        }

        /// <summary>
        /// Writes the opening <c>namespace ABI.X</c> block plus the <c>#pragma warning disable CA1416</c>
        /// suppression that wraps every ABI namespace.
        /// </summary>
        /// <param name="context">The active emit context (provides the namespace).</param>
        public void WriteBeginAbiNamespace(ProjectionEmitContext context)
        {
            writer.WriteLine();
            writer.Write($$"""
                #pragma warning disable CA1416
                namespace ABI.{{context.CurrentNamespace}}
                {
                """, isMultiline: true);
            writer.IncreaseIndent();
        }

        /// <summary>
        /// Writes the closing <c>}</c> for the ABI namespace plus the matching
        /// <c>#pragma warning restore CA1416</c>.
        /// </summary>
        public void WriteEndAbiNamespace()
        {
            writer.DecreaseIndent();
            writer.WriteLine("""
                }
                #pragma warning restore CA1416
                """, isMultiline: true);
        }
    }
}
