// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using WindowsRuntime.ProjectionWriter.Writers;

namespace WindowsRuntime.ProjectionWriter.Extensions;

/// <summary>
/// WinRT-projection-specific emission helpers for <see cref="IndentedTextWriter"/>: file header,
/// projected/ABI namespace blocks, and pragma sections.
/// </summary>
/// <remarks>
/// These helpers are layered on top of the general-purpose <see cref="IndentedTextWriter"/> as
/// extension methods that take a <see cref="ProjectionEmitContext"/> for the per-emission state
/// (settings + namespace). They are the long-term replacement for the equivalent methods that
/// historically lived on the legacy <c>TypeWriter</c> surface; during Pass 10 the
/// <c>TypeWriter</c> instance methods just delegate here.
/// </remarks>
internal static class ProjectionWriterExtensions
{
    /// <summary>
    /// Writes the standard auto-generated file header (the C++ <c>cswinrt.exe</c> banner +
    /// canonical <c>using</c> imports + suppression pragmas) at the top of every emitted
    /// <c>.cs</c> file.
    /// </summary>
    /// <param name="writer">The writer to emit to.</param>
    /// <param name="context">The active emit context (currently unused, but reserved for future per-namespace customization).</param>
    public static void WriteFileHeader(this IndentedTextWriter writer, ProjectionEmitContext context)
    {
        _ = context;
        writer.WriteLine("//------------------------------------------------------------------------------");
        writer.WriteLine("// <auto-generated>");
        writer.Write("//     This file was generated by cswinrt.exe version ");
        writer.Write(MetadataAttributeFactory.GetVersionString());
        writer.WriteLine("");
        writer.WriteLine("//");
        writer.WriteLine("//     Changes to this file may cause incorrect behavior and will be lost if");
        writer.WriteLine("//     the code is regenerated.");
        writer.WriteLine("// </auto-generated>");
        writer.WriteLine("//------------------------------------------------------------------------------");
        writer.WriteLine("\r");
        writer.WriteLine("using System;\r");
        writer.WriteLine("using System.Collections;\r");
        writer.WriteLine("using System.Collections.Generic;\r");
        writer.WriteLine("using System.Collections.ObjectModel;\r");
        writer.WriteLine("using System.ComponentModel;\r");
        writer.WriteLine("using System.Diagnostics;\r");
        writer.WriteLine("using System.Diagnostics.CodeAnalysis;\r");
        writer.WriteLine("using System.Runtime.CompilerServices;\r");
        writer.WriteLine("using System.Runtime.InteropServices;\r");
        writer.WriteLine("using Windows.Foundation;\r");
        writer.WriteLine("using WindowsRuntime;\r");
        writer.WriteLine("using WindowsRuntime.InteropServices;\r");
        writer.WriteLine("using WindowsRuntime.InteropServices.Marshalling;\r");
        writer.WriteLine("using static System.Runtime.InteropServices.ComWrappers;\r");
        writer.WriteLine("\r");
        writer.WriteLine("#pragma warning disable CS0169 // \"The field '...' is never used\"\r");
        writer.WriteLine("#pragma warning disable CS0649 // \"Field '...' is never assigned to\"\r");
        writer.WriteLine("#pragma warning disable CA2207, CA1063, CA1033, CA1001, CA2213\r");
        writer.WriteLine("#pragma warning disable CSWINRT3001 // \"Type or member '...' is a private implementation detail\"\r");
        writer.WriteLine("#pragma warning disable CS8500 // This takes the address of, gets the size of, or declares a pointer to a managed type\r");
        writer.WriteLine("\r");
    }

    /// <summary>
    /// Writes the opening <c>namespace ...</c> block for the projected namespace (with the
    /// <c>ABI.Impl.</c> prefix when emitting a Windows Runtime component projection).
    /// </summary>
    /// <param name="writer">The writer to emit to.</param>
    /// <param name="context">The active emit context (provides the namespace + component flag).</param>
    public static void WriteBeginProjectedNamespace(this IndentedTextWriter writer, ProjectionEmitContext context)
    {
        string nsPrefix = context.Settings.Component ? "ABI.Impl." : string.Empty;
        writer.Write($"\nnamespace {nsPrefix}{context.CurrentNamespace}\n{{\n");
    }

    /// <summary>Writes the closing <c>}</c> for the projected namespace.</summary>
    /// <param name="writer">The writer to emit to.</param>
    public static void WriteEndProjectedNamespace(this IndentedTextWriter writer)
    {
        writer.WriteLine("}");
    }

    /// <summary>
    /// Writes the opening <c>namespace ABI.X</c> block plus the <c>#pragma warning disable CA1416</c>
    /// suppression that wraps every ABI namespace.
    /// </summary>
    /// <param name="writer">The writer to emit to.</param>
    /// <param name="context">The active emit context (provides the namespace).</param>
    public static void WriteBeginAbiNamespace(this IndentedTextWriter writer, ProjectionEmitContext context)
    {
        writer.Write($"\n#pragma warning disable CA1416\nnamespace ABI.{context.CurrentNamespace}\n{{\n");
    }

    /// <summary>
    /// Writes the closing <c>}</c> for the ABI namespace plus the matching
    /// <c>#pragma warning restore CA1416</c>.
    /// </summary>
    /// <param name="writer">The writer to emit to.</param>
    public static void WriteEndAbiNamespace(this IndentedTextWriter writer)
    {
        writer.WriteLine("}");
        writer.WriteLine("#pragma warning restore CA1416");
    }
}