<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(DotNetVersion)</TargetFramework>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>

    <!-- Common metadata properties for publishing -->
    <Description>C#/WinRT Projection Generator v$(VersionString)</Description>
    <AssemblyTitle>C#/WinRT Projection Generator v$(VersionString)</AssemblyTitle>
    <Copyright>Copyright (c) Microsoft Corporation. All rights reserved.</Copyright>
    <AssemblyVersion>$(AssemblyVersionNumber)</AssemblyVersion>
    <FileVersion>$(VersionNumber)</FileVersion>

    <!-- Set the root namespace to match the other projects -->
    <RootNamespace>WindowsRuntime.ProjectionGenerator</RootNamespace>

    <!-- This project produces a CLI tool, so we want a nice short name for it -->
    <AssemblyName>cswinrtprojectiongen</AssemblyName>
      
    <!-- Used to enable publishing project in build -->
    <IsBuildTool>true</IsBuildTool>
    <RuntimeIdentifier Condition="'$(PublishBuildTool)' == 'true'">win-$(BuildToolArch)</RuntimeIdentifier>
    <SelfContained Condition="'$(PublishBuildTool)' == 'true'">true</SelfContained>

    <!-- Suppress trim/AOT analyzer warnings from the 'Microsoft.CodeAnalysis.CSharp' reference (Roslyn is not trim-safe) -->
    <NoWarn>$(NoWarn);IL2091;IL2050;IL2072;IL2075;IL2026</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WinRT.Generator.Core\WinRT.Generator.Core.csproj" />
    <ProjectReference Include="..\WinRT.Projection.Writer\WinRT.Projection.Writer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ConsoleAppFramework" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
  </ItemGroup>
</Project>
