<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <PackageId>CsWinRT.SmokeTests.PrivateAssetsLibrary</PackageId>
    <CsWinRTSmokeTestPackageReference>false</CsWinRTSmokeTestPackageReference>
    <RestoreAdditionalProjectSources>$(PrivateAssetsPackageSource)</RestoreAdditionalProjectSources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsWinRT.SmokeTests.PrivateAssetsDependency"
                      Version="$(PrivateAssetsPackageVersion)"
                      PrivateAssets="all" />
  </ItemGroup>
</Project>
