// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System;
using System.IO;
using System.Text;
using AsmResolver.DotNet;

namespace WindowsRuntime.ProjectionGenerator.Generation;

/// <inheritdoc cref="ProjectionGenerator"/>
internal partial class ProjectionGenerator
{
    /// <summary>
    /// Component-mode only. Emits the supporting source files that make <c>WinRT.Component.dll</c>
    /// the merged aggregator dll: (a) a module initializer that designates this assembly as the
    /// entry assembly for .NET TypeMap discovery, (b) a <c>[TypeMapAssemblyTarget]</c> union
    /// covering each component plus shared infrastructure assemblies, and (c) a merged
    /// <c>ABI.WinRT.Component.ManagedExports.GetActivationFactory</c> that the
    /// <c>WinRT.Host.Shim</c> reflects on.
    /// </summary>
    /// <remarks>
    /// These emissions write directly into <see cref="ProjectionGeneratorProcessingState.SourcesFolder"/>
    /// (the same folder cswinrt.exe targets), so they are picked up automatically by the
    /// Roslyn compile step in <see cref="Emit"/>.
    /// </remarks>
    private static void EmitWinRTComponentSources(ProjectionGeneratorArgs args, ProjectionGeneratorProcessingState processingState)
    {
        // Only emit these files when producing 'WinRT.Component.dll'.
        if (args.AssemblyName != "WinRT.Component")
        {
            return;
        }

        // Nothing to merge if there are no input components. cswinrt.exe -component would
        // not have produced any 'ABI.{ComponentName}.ManagedExports' types either.
        if (processingState.ComponentAssemblyNames.Count == 0)
        {
            return;
        }

        WriteProjectionTypesInitializer(processingState);
        WriteTypeMapAssemblyTargets(args, processingState);

        // The merged ABI.WinRT.Component.ManagedExports.GetActivationFactory dispatcher and its
        // 'string' reflection-friendly overload are emitted by the source generator's
        // EmitManagedExports path when the aggregator csproj has
        // CsWinRTMergeReferencedActivationFactories=true (and IsComponent=false). Same for the
        // [UnmanagedCallersOnly] DllGetActivationFactory native export under PublishAot. We only
        // need to emit the projection-init module ctor and the TypeMap union here.
    }

    /// <summary>
    /// Emits a <c>[ModuleInitializer]</c>-driven <c>SetEntryAssembly</c> in <c>WinRT.Component.dll</c>.
    /// This designates <c>WinRT.Component.dll</c> as the entry assembly the .NET runtime uses
    /// to root <c>[TypeMapAssemblyTarget]</c> discovery. Idempotent: skipped if the host has
    /// already set an entry assembly. Per-component dlls intentionally do not emit a similar
    /// initializer; consumers using a single component dll directly must call
    /// <c>Assembly.SetEntryAssembly</c> themselves if they need TypeMap discovery rooted there.
    /// </summary>
    private static void WriteProjectionTypesInitializer(ProjectionGeneratorProcessingState processingState)
    {
        const string source = """
            // <auto-generated/>
            #pragma warning disable

            namespace ABI.WinRT.Component;

            /// <summary>
            /// Designates <c>WinRT.Component.dll</c> as the entry assembly for the hosted .NET
            /// runtime so that <c>[TypeMapAssemblyTarget]</c> discovery (rooted at the entry
            /// assembly) sees the union assembly attributes emitted on this dll.
            /// </summary>
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            internal static class ProjectionTypesInitializer
            {
            #pragma warning disable CA2255 // The 'ModuleInitializer' attribute should not be used in libraries
                [global::System.Runtime.CompilerServices.ModuleInitializer]
            #pragma warning restore CA2255
                internal static void InitializeProjectionTypes()
                {
                    if (global::System.Reflection.Assembly.GetEntryAssembly() is null)
                    {
                        global::System.Reflection.Assembly.SetEntryAssembly(typeof(ProjectionTypesInitializer).Assembly);
                    }
                }
            }
            """;

        File.WriteAllText(Path.Combine(processingState.SourcesFolder, "ProjectionTypesInitializer.g.cs"), source);
    }

    /// <summary>
    /// Emits the union <c>[TypeMapAssemblyTarget]</c> assembly attributes on
    /// <c>WinRT.Component.dll</c>. The union covers each input component, the shared CsWinRT
    /// infrastructure assemblies (<c>WinRT.Interop</c>, <c>WinRT.Runtime</c>,
    /// <c>WinRT.Sdk.Projection</c>), and (when applicable) <c>WinRT.Sdk.Xaml.Projection</c>
    /// and <c>WinRT.Projection</c>.
    /// </summary>
    /// <remarks>
    /// Only assemblies that will actually be deployed alongside <c>WinRT.Component.dll</c> are
    /// included. The .NET runtime fails with <see cref="FileNotFoundException"/> when it tries
    /// to enumerate a target assembly that doesn't exist, which would in turn fail the static
    /// constructor of any type that depends on the type map (e.g. <c>WindowsRuntimeComWrappers</c>).
    /// </remarks>
    private static void WriteTypeMapAssemblyTargets(ProjectionGeneratorArgs args, ProjectionGeneratorProcessingState processingState)
    {
        // Build the list of target assembly simple names. Order is deterministic for stable
        // codegen output. The runtime treats the order as irrelevant for discovery.
        System.Collections.Generic.List<string> targetAssemblyNames =
        [
            "WinRT.Interop",
            "WinRT.Runtime",
            "WinRT.Sdk.Projection",
        ];

        if (args.WindowsUIXamlProjection)
        {
            targetAssemblyNames.Add("WinRT.Sdk.Xaml.Projection");
        }

        // 'WinRT.Projection.dll' is generated only when there are non-Windows-SDK, non-component
        // Windows Runtime reference assemblies in scope (i.e. third-party projection references).
        // Only include it in the union when that condition holds; otherwise the runtime would
        // fail with FileNotFoundException trying to enumerate a non-existent assembly.
        if (HasMergedProjectionReferences(args))
        {
            targetAssemblyNames.Add("WinRT.Projection");
        }

        // Per-component targets
        targetAssemblyNames.AddRange(processingState.ComponentAssemblyNames);

        StringBuilder sb = new();
        _ = sb.AppendLine("// <auto-generated/>");
        _ = sb.AppendLine("#pragma warning disable");
        _ = sb.AppendLine();

        foreach (string targetTypeMapGroup in (string[])
        [
            "global::WindowsRuntime.InteropServices.WindowsRuntimeComWrappersTypeMapGroup",
            "global::WindowsRuntime.InteropServices.WindowsRuntimeMetadataTypeMapGroup",
            "global::WindowsRuntime.InteropServices.DynamicInterfaceCastableImplementationTypeMapGroup",
        ])
        {
            foreach (string targetAssembly in targetAssemblyNames)
            {
                _ = sb.AppendLine($"[assembly: global::System.Runtime.InteropServices.TypeMapAssemblyTarget<{targetTypeMapGroup}>(\"{targetAssembly}\")]");
            }

            _ = sb.AppendLine();
        }

        File.WriteAllText(Path.Combine(processingState.SourcesFolder, "TypeMapAssemblyTargets.g.cs"), sb.ToString());
    }

    /// <summary>
    /// Returns <c>true</c> if there is at least one non-Windows-SDK, non-component Windows Runtime
    /// reference assembly in scope - i.e. the same condition the merged projection target
    /// uses to determine whether <c>WinRT.Projection.dll</c> needs to be generated.
    /// </summary>
    private static bool HasMergedProjectionReferences(ProjectionGeneratorArgs args)
    {
        string[] resolverPaths = [.. System.Linq.Enumerable.Where(args.ReferenceAssemblyPaths,
            p => !p.EndsWith(".winmd", StringComparison.OrdinalIgnoreCase))];

        PathAssemblyResolver resolver = new(resolverPaths);

        foreach (string refPath in args.ReferenceAssemblyPaths)
        {
            if (refPath.EndsWith(".winmd", StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            ModuleDefinition refModule;

            try
            {
                refModule = ModuleDefinition.FromFile(refPath, resolver.ReaderParameters);
            }
            catch
            {
                continue;
            }

            // Skip non-projection references (only WinRT projection .dll-s are interesting)
            if (!IsReferenceAssembly(refModule) || !IsWindowsRuntimeReferenceAssembly(refModule))
            {
                continue;
            }

            // Windows SDK projections (Microsoft.Windows.SDK.NET / Microsoft.Windows.UI.Xaml)
            // go into 'WinRT.Sdk.Projection.dll' / 'WinRT.Sdk.Xaml.Projection.dll', not 'WinRT.Projection.dll'.
            if (IsWindowsSdkAssembly(refModule))
            {
                continue;
            }

            // Component reference projections also don't go into 'WinRT.Projection.dll' (they
            // are listed separately in the per-component target group above).
            if (IsComponentAssembly(refModule))
            {
                continue;
            }

            // A third-party Windows Runtime reference projection - 'WinRT.Projection.dll' will
            // be generated by '_RunCsWinRTMergedProjectionGenerator' for these.
            return true;
        }

        return false;
    }
}
