// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using AsmResolver.DotNet;
using WindowsRuntime.ProjectionWriter.Writers;

namespace WindowsRuntime.ProjectionGenerator.Generation;

/// <inheritdoc cref="ProjectionGenerator"/>
internal partial class ProjectionGenerator
{
    /// <summary>
    /// Component-mode only. Emits the supporting source files that make <c>WinRT.Component.dll</c>
    /// the merged aggregator dll:
    /// <list type="bullet">
    ///   <item>
    ///     A <see cref="System.Runtime.InteropServices.TypeMapAssemblyTargetAttribute{TTypeMapGroup}"/>
    ///     union covering each component plus shared infrastructure assemblies.
    ///   </item>
    ///   <item>
    ///     A merged <c>ABI.WinRT.Component.ManagedExports.GetActivationFactory</c> that <c>WinRT.Host.Shim</c> reflects on.
    ///   </item>
    /// </list>
    /// </summary>
    /// <remarks>
    /// These emissions write directly into <see cref="ProjectionGeneratorProcessingState.SourcesFolder"/>
    /// (the same folder cswinrt.exe targets), so they are picked up automatically by the Roslyn compile
    /// step in <see cref="Emit"/>.
    /// </remarks>
    private static void EmitWinRTComponentSources(ProjectionGeneratorArgs args, ProjectionGeneratorProcessingState processingState)
    {
        // Only emit these files when producing 'WinRT.Component.dll'
        if (args.AssemblyName != "WinRT.Component")
        {
            return;
        }

        // Nothing to merge if there are no input components. In this case, the
        // projection generator invocation in component mode would not have produced
        // any 'ABI.{ComponentName}.ManagedExports' types either.
        if (processingState.ComponentAssemblyNames.Count == 0)
        {
            return;
        }

        WriteTypeMapAssemblyTargets(args, processingState);
        WriteMergedManagedExports(processingState);
    }

    /// <summary>
    /// Emits the union <c>[TypeMapAssemblyTarget]</c> assembly attributes on
    /// <c>WinRT.Component.dll</c>. The union covers each input component, the shared CsWinRT
    /// infrastructure assemblies (<c>WinRT.Interop</c>, <c>WinRT.Runtime</c>,
    /// <c>WinRT.Sdk.Projection</c>), and (when applicable) <c>WinRT.Sdk.Xaml.Projection</c>
    /// and <c>WinRT.Projection</c>.
    /// </summary>
    /// <remarks>
    /// Only assemblies that will actually be deployed alongside <c>WinRT.Component.dll</c> are
    /// included. The .NET runtime fails with <see cref="FileNotFoundException"/> when it tries
    /// to enumerate a target assembly that doesn't exist, which would in turn fail the static
    /// constructor of any type that depends on the type map (e.g. <c>WindowsRuntimeComWrappers</c>).
    /// </remarks>
    private static void WriteTypeMapAssemblyTargets(ProjectionGeneratorArgs args, ProjectionGeneratorProcessingState processingState)
    {
        // Build the list of target assembly simple names. Order is deterministic for stable
        // codegen output. The runtime treats the order as irrelevant for discovery.
        List<string> targetAssemblyNames =
        [
            "WinRT.Interop",
            "WinRT.Runtime",
            "WinRT.Sdk.Projection",
        ];

        if (args.WindowsUIXamlProjection)
        {
            targetAssemblyNames.Add("WinRT.Sdk.Xaml.Projection");
        }

        // 'WinRT.Projection.dll' is generated only when there are non-Windows-SDK, non-component
        // Windows Runtime reference assemblies in scope (i.e. third-party projection references).
        // Only include it in the union when that condition holds, otherwise the runtime would
        // fail with 'FileNotFoundException' trying to enumerate a non-existent assembly.
        if (HasMergedProjectionReferences(args))
        {
            targetAssemblyNames.Add("WinRT.Projection");
        }

        // Per-component targets
        targetAssemblyNames.AddRange(processingState.ComponentAssemblyNames);

        StringBuilder builder = new();

        _ = builder.AppendLine("// <auto-generated/>");
        _ = builder.AppendLine("#pragma warning disable");
        _ = builder.AppendLine();

        // Append all interop type map entries for each target assembly we discovered
        foreach (string targetTypeMapGroup in (ReadOnlySpan<string>)[
            "global::WindowsRuntime.InteropServices.WindowsRuntimeComWrappersTypeMapGroup",
            "global::WindowsRuntime.InteropServices.WindowsRuntimeMetadataTypeMapGroup",
            "global::WindowsRuntime.InteropServices.DynamicInterfaceCastableImplementationTypeMapGroup"])
        {
            foreach (string targetAssembly in targetAssemblyNames)
            {
                _ = builder.AppendLine($"[assembly: global::System.Runtime.InteropServices.TypeMapAssemblyTarget<{targetTypeMapGroup}>(\"{targetAssembly}\")]");
            }
        }

        string destinationPath = Path.Combine(processingState.SourcesFolder, "TypeMapAssemblyTargets.g.cs");

        File.WriteAllText(destinationPath, builder.ToString());
    }

    /// <summary>
    /// Returns <c>true</c> if there is at least one non-Windows-SDK, non-component Windows Runtime
    /// reference assembly in scope - i.e. the same condition the merged projection target
    /// uses to determine whether <c>WinRT.Projection.dll</c> needs to be generated.
    /// </summary>
    private static bool HasMergedProjectionReferences(ProjectionGeneratorArgs args)
    {
        string[] resolverPaths = [.. args.ReferenceAssemblyPaths.Where(p => !p.EndsWith(".winmd", StringComparison.OrdinalIgnoreCase))];

        PathAssemblyResolver resolver = new(resolverPaths);

        foreach (string refPath in args.ReferenceAssemblyPaths)
        {
            if (refPath.EndsWith(".winmd", StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            ModuleDefinition refModule;

            try
            {
                refModule = ModuleDefinition.FromFile(refPath, resolver.ReaderParameters);
            }
            catch
            {
                continue;
            }

            // Skip non-projection references (only WinRT projection .dll-s are interesting)
            if (!IsReferenceAssembly(refModule) || !IsWindowsRuntimeReferenceAssembly(refModule))
            {
                continue;
            }

            // Windows SDK projections ('Microsoft.Windows.SDK.NET' and 'Microsoft.Windows.UI.Xaml') go into
            // 'WinRT.Sdk.Projection.dll' and 'WinRT.Sdk.Xaml.Projection.dll', not 'WinRT.Projection.dll'.
            if (IsWindowsSdkAssembly(refModule))
            {
                continue;
            }

            // Component reference projections also don't go into 'WinRT.Projection.dll'
            // (they are listed separately in the per-component target group above).
            if (IsComponentAssembly(refModule))
            {
                continue;
            }

            // A third-party Windows Runtime reference projection, 'WinRT.Projection.dll'
            // will be generated by '_RunCsWinRTMergedProjectionGenerator' for these.
            return true;
        }

        return false;
    }

    /// <summary>
    /// Emits <c>ABI.WinRT.Component.ManagedExports.GetActivationFactory</c>, a merged dispatcher
    /// that walks each per-component <c>ABI.{ComponentName}.ManagedExports.GetActivationFactory</c>
    /// (already emitted by the projection generator invocation in component mode) and returns the
    /// first non-<see langword="null"/> factory.
    /// </summary>
    /// <remarks>
    /// This type is what <c>WinRT.Host.Shim.GetActivationFactory</c> reflects on when the
    /// loaded target assembly is <c>WinRT.Component.dll</c> (the moduleName the shim
    /// computes from the '.dll' filename is <c>"WinRT.Component"</c>, so it looks up
    /// <c>ABI.WinRT.Component.ManagedExports</c>).
    /// </remarks>
    private static void WriteMergedManagedExports(ProjectionGeneratorProcessingState processingState)
    {
        IndentedTextWriter writer = new();

        // Writes the invocations to all available components for the current type being activated
        void WriteActivationFactoryInvocations(IndentedTextWriter writer)
        {
            foreach (string componentAssemblyName in processingState.ComponentAssemblyNames)
            {
                writer.WriteLine($$"""
                factory = global::ABI.{{componentAssemblyName}}.ManagedExports.GetActivationFactory(activatableClassId);
                if (factory is not null)
                {
                    return factory;
                }
                """);
            }
        }

        // Write the managed exports for 'GetActivationFactory'
        writer.WriteLine($$"""
            // <auto-generated/>
            #pragma warning disable
            
            namespace ABI.WinRT.Component;
            
            /// <summary>
            /// Merged managed activation entry point for <c>WinRT.Component.dll</c>. Reflectively
            /// invoked by <c>WinRT.Host.Shim.GetActivationFactory</c> when the manifest-free
            /// activation flow loads <c>WinRT.Component.dll</c>; iterates per-component
            /// <c>ABI.{ComponentName}.ManagedExports.GetActivationFactory</c> entries.
            /// </summary>
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            public static unsafe class ManagedExports
            {
                /// <summary>
                /// Retrieves the activation factory for the requested runtime class by
                /// dispatching to each input component's <c>ManagedExports</c> in turn.
                /// </summary>
                /// <param name="activatableClassId">The runtime class identifier.</param>
                /// <returns>A pointer to the factory, or <see langword="null"/> if no component handles the class.</returns>
                public static void* GetActivationFactory(global::System.ReadOnlySpan<char> activatableClassId)
                {
                    void* factory;

                    {{WriteActivationFactoryInvocations}}
            
                    return null;
                }
            
                /// <summary>
                /// Reflection-friendly overload used by managed runtime hosts (e.g. <c>WinRT.Host.Shim</c>).
                /// </summary>
                /// <param name="activatableClassId">The runtime class identifier.</param>
                /// <returns>A pointer to the factory, or <see langword="default"/> if no component handles the class.</returns>
                public static nint GetActivationFactory(string activatableClassId)
                {
                    return (nint)GetActivationFactory(global::System.MemoryExtensions.AsSpan(activatableClassId));
                }
            }
            """);

        string destinationPath = Path.Combine(processingState.SourcesFolder, "MergedManagedExports.g.cs");

        writer.FlushToFile(destinationPath);
    }
}
