// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System;
using System.IO;
using System.Text;
using AsmResolver.DotNet;

namespace WindowsRuntime.ProjectionGenerator.Generation;

/// <inheritdoc cref="ProjectionGenerator"/>
internal partial class ProjectionGenerator
{
    /// <summary>
    /// Component-mode only. Emits the auxiliary source files for <c>WinRT.Component.dll</c>:
    /// (a) a module initializer that designates this assembly as the entry assembly for
    /// .NET TypeMap discovery, (b) a <c>[TypeMapAssemblyTarget]</c> union covering each
    /// component plus shared infrastructure assemblies, (c) a merged
    /// <c>ABI.WinRT.Component.ManagedExports.GetActivationFactory</c> that the
    /// <c>WinRT.Host.Shim</c> reflects on, and (d, AOT only) a C-callable
    /// <c>DllGetActivationFactory</c> export wrapping the merged factory.
    /// </summary>
    /// <remarks>
    /// These emissions write directly into <see cref="ProjectionGeneratorProcessingState.SourcesFolder"/>
    /// (the same folder cswinrt.exe targets), so they are picked up automatically by the
    /// Roslyn compile step in <see cref="Emit"/>.
    /// </remarks>
    private static void EmitAuxiliaryComponentSources(ProjectionGeneratorArgs args, ProjectionGeneratorProcessingState processingState)
    {
        // Only emit these files when producing 'WinRT.Component.dll'.
        if (args.AssemblyName != "WinRT.Component")
        {
            return;
        }

        // Nothing to merge if there are no input components. cswinrt.exe -component would
        // not have produced any 'ABI.{ComponentName}.ManagedExports' types either.
        if (processingState.ComponentAssemblyNames.Count == 0)
        {
            return;
        }

        WriteProjectionTypesInitializer(processingState);
        WriteTypeMapAssemblyTargets(args, processingState);
        WriteMergedManagedExports(processingState);

        if (args.PublishAot)
        {
            WriteNativeExports(processingState);
        }
    }

    /// <summary>
    /// Emits a <c>[ModuleInitializer]</c>-driven <c>SetEntryAssembly</c> in <c>WinRT.Component.dll</c>.
    /// This designates <c>WinRT.Component.dll</c> as the entry assembly the .NET runtime uses
    /// to root <c>[TypeMapAssemblyTarget]</c> discovery. Idempotent: skipped if the host has
    /// already set an entry assembly. Per-component dlls intentionally do not emit a similar
    /// initializer; consumers using a single component dll directly must call
    /// <c>Assembly.SetEntryAssembly</c> themselves if they need TypeMap discovery rooted there.
    /// </summary>
    private static void WriteProjectionTypesInitializer(ProjectionGeneratorProcessingState processingState)
    {
        const string source = """
            // <auto-generated/>
            #pragma warning disable

            namespace ABI.WinRT.Component;

            /// <summary>
            /// Designates <c>WinRT.Component.dll</c> as the entry assembly for the hosted .NET
            /// runtime so that <c>[TypeMapAssemblyTarget]</c> discovery (rooted at the entry
            /// assembly) sees the union assembly attributes emitted on this dll.
            /// </summary>
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            internal static class ProjectionTypesInitializer
            {
            #pragma warning disable CA2255 // The 'ModuleInitializer' attribute should not be used in libraries
                [global::System.Runtime.CompilerServices.ModuleInitializer]
            #pragma warning restore CA2255
                internal static void InitializeProjectionTypes()
                {
                    if (global::System.Reflection.Assembly.GetEntryAssembly() is null)
                    {
                        global::System.Reflection.Assembly.SetEntryAssembly(typeof(ProjectionTypesInitializer).Assembly);
                    }
                }
            }
            """;

        File.WriteAllText(Path.Combine(processingState.SourcesFolder, "ProjectionTypesInitializer.g.cs"), source);
    }

    /// <summary>
    /// Emits the union <c>[TypeMapAssemblyTarget]</c> assembly attributes on
    /// <c>WinRT.Component.dll</c>. The union covers each input component, the shared CsWinRT
    /// infrastructure assemblies (<c>WinRT.Interop</c>, <c>WinRT.Runtime</c>,
    /// <c>WinRT.Sdk.Projection</c>), and (when applicable) <c>WinRT.Sdk.Xaml.Projection</c>
    /// and <c>WinRT.Projection</c>.
    /// </summary>
    /// <remarks>
    /// Only assemblies that will actually be deployed alongside <c>WinRT.Component.dll</c> are
    /// included. The .NET runtime fails with <see cref="FileNotFoundException"/> when it tries
    /// to enumerate a target assembly that doesn't exist, which would in turn fail the static
    /// constructor of any type that depends on the type map (e.g. <c>WindowsRuntimeComWrappers</c>).
    /// </remarks>
    private static void WriteTypeMapAssemblyTargets(ProjectionGeneratorArgs args, ProjectionGeneratorProcessingState processingState)
    {
        // Build the list of target assembly simple names. Order is deterministic for stable
        // codegen output. The runtime treats the order as irrelevant for discovery.
        System.Collections.Generic.List<string> targetAssemblyNames =
        [
            "WinRT.Interop",
            "WinRT.Runtime",
            "WinRT.Sdk.Projection",
        ];

        if (args.WindowsUIXamlProjection)
        {
            targetAssemblyNames.Add("WinRT.Sdk.Xaml.Projection");
        }

        // 'WinRT.Projection.dll' is generated only when there are non-Windows-SDK, non-component
        // Windows Runtime reference assemblies in scope (i.e. third-party projection references).
        // Only include it in the union when that condition holds; otherwise the runtime would
        // fail with FileNotFoundException trying to enumerate a non-existent assembly.
        if (HasMergedProjectionReferences(args, processingState))
        {
            targetAssemblyNames.Add("WinRT.Projection");
        }

        // Per-component targets
        targetAssemblyNames.AddRange(processingState.ComponentAssemblyNames);

        StringBuilder sb = new();
        _ = sb.AppendLine("// <auto-generated/>");
        _ = sb.AppendLine("#pragma warning disable");
        _ = sb.AppendLine();

        foreach (string targetTypeMapGroup in (string[])
        [
            "global::WindowsRuntime.InteropServices.WindowsRuntimeComWrappersTypeMapGroup",
            "global::WindowsRuntime.InteropServices.WindowsRuntimeMetadataTypeMapGroup",
            "global::WindowsRuntime.InteropServices.DynamicInterfaceCastableImplementationTypeMapGroup",
        ])
        {
            foreach (string targetAssembly in targetAssemblyNames)
            {
                _ = sb.Append("[assembly: global::System.Runtime.InteropServices.TypeMapAssemblyTarget<")
                       .Append(targetTypeMapGroup)
                       .Append(">(\"")
                       .Append(targetAssembly)
                       .AppendLine("\")]");
            }

            _ = sb.AppendLine();
        }

        File.WriteAllText(Path.Combine(processingState.SourcesFolder, "TypeMapAssemblyTargets.g.cs"), sb.ToString());
    }

    /// <summary>
    /// Returns <c>true</c> if there is at least one non-Windows-SDK, non-component Windows Runtime
    /// reference assembly in scope - i.e. the same condition the merged projection target
    /// uses to determine whether <c>WinRT.Projection.dll</c> needs to be generated.
    /// </summary>
    private static bool HasMergedProjectionReferences(ProjectionGeneratorArgs args, ProjectionGeneratorProcessingState processingState)
    {
        _ = processingState;
        string[] resolverPaths = [.. System.Linq.Enumerable.Where(args.ReferenceAssemblyPaths,
            p => !p.EndsWith(".winmd", StringComparison.OrdinalIgnoreCase))];

        PathAssemblyResolver resolver = new(resolverPaths);

        foreach (string refPath in args.ReferenceAssemblyPaths)
        {
            if (refPath.EndsWith(".winmd", StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            ModuleDefinition refModule;

            try
            {
                refModule = ModuleDefinition.FromFile(refPath, resolver.ReaderParameters);
            }
            catch
            {
                continue;
            }

            // Skip non-projection references (only WinRT projection .dll-s are interesting)
            if (!IsReferenceAssembly(refModule) || !IsWindowsRuntimeReferenceAssembly(refModule))
            {
                continue;
            }

            // Windows SDK projections (Microsoft.Windows.SDK.NET / Microsoft.Windows.UI.Xaml)
            // go into 'WinRT.Sdk.Projection.dll' / 'WinRT.Sdk.Xaml.Projection.dll', not 'WinRT.Projection.dll'.
            if (IsWindowsSdkAssembly(refModule))
            {
                continue;
            }

            // Component reference projections also don't go into 'WinRT.Projection.dll' (they
            // are listed separately in the per-component target group above).
            if (IsComponentAssembly(refModule))
            {
                continue;
            }

            // A third-party Windows Runtime reference projection - 'WinRT.Projection.dll' will
            // be generated by '_RunCsWinRTMergedProjectionGenerator' for these.
            return true;
        }

        return false;
    }

    /// <summary>
    /// Emits <c>ABI.WinRT.Component.ManagedExports.GetActivationFactory</c>, a merged
    /// dispatcher that walks each per-component <c>ABI.{ComponentName}.ManagedExports.GetActivationFactory</c>
    /// (already emitted by cswinrt.exe in <c>-component</c> mode) and returns the first
    /// non-<c>null</c> factory.
    /// </summary>
    /// <remarks>
    /// This type is what <c>WinRT.Host.Shim.GetActivationFactory</c> reflects on when the
    /// loaded target assembly is <c>WinRT.Component.dll</c> (the moduleName the shim
    /// computes from the dll filename is <c>"WinRT.Component"</c>, so it looks up
    /// <c>ABI.WinRT.Component.ManagedExports</c>).
    /// </remarks>
    private static void WriteMergedManagedExports(ProjectionGeneratorProcessingState processingState)
    {
        StringBuilder sb = new();

        _ = sb.AppendLine("// <auto-generated/>");
        _ = sb.AppendLine("#pragma warning disable");
        _ = sb.AppendLine();
        _ = sb.AppendLine("namespace ABI.WinRT.Component;");
        _ = sb.AppendLine();
        _ = sb.AppendLine("/// <summary>");
        _ = sb.AppendLine("/// Merged managed activation entry point for <c>WinRT.Component.dll</c>. Reflectively");
        _ = sb.AppendLine("/// invoked by <c>WinRT.Host.Shim.GetActivationFactory</c> when the manifest-free");
        _ = sb.AppendLine("/// activation flow loads <c>WinRT.Component.dll</c>; iterates per-component");
        _ = sb.AppendLine("/// <c>ABI.{ComponentName}.ManagedExports.GetActivationFactory</c> entries.");
        _ = sb.AppendLine("/// </summary>");
        _ = sb.AppendLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        _ = sb.AppendLine("public static unsafe class ManagedExports");
        _ = sb.AppendLine("{");
        _ = sb.AppendLine("    /// <summary>");
        _ = sb.AppendLine("    /// Retrieves the activation factory for the requested runtime class by");
        _ = sb.AppendLine("    /// dispatching to each input component's <c>ManagedExports</c> in turn.");
        _ = sb.AppendLine("    /// </summary>");
        _ = sb.AppendLine("    /// <param name=\"activatableClassId\">The runtime class identifier.</param>");
        _ = sb.AppendLine("    /// <returns>A pointer to the factory, or <c>null</c> if no component handles the class.</returns>");
        _ = sb.AppendLine("    public static void* GetActivationFactory(global::System.ReadOnlySpan<char> activatableClassId)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        void* factory;");

        foreach (string componentAssemblyName in processingState.ComponentAssemblyNames)
        {
            _ = sb.AppendLine();
            _ = sb.Append("        factory = global::ABI.")
                   .Append(componentAssemblyName)
                   .AppendLine(".ManagedExports.GetActivationFactory(activatableClassId);");
            _ = sb.AppendLine("        if (factory is not null)");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            return factory;");
            _ = sb.AppendLine("        }");
        }

        _ = sb.AppendLine();
        _ = sb.AppendLine("        return null;");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    /// <summary>");
        _ = sb.AppendLine("    /// Reflection-friendly overload used by managed runtime hosts (e.g. <c>WinRT.Host.Shim</c>).");
        _ = sb.AppendLine("    /// </summary>");
        _ = sb.AppendLine("    public static nint GetActivationFactory(string activatableClassId)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        return (nint)GetActivationFactory(global::System.MemoryExtensions.AsSpan(activatableClassId));");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine("}");

        File.WriteAllText(Path.Combine(processingState.SourcesFolder, "MergedManagedExports.g.cs"), sb.ToString());
    }

    /// <summary>
    /// (AOT only) Emits the C-callable <c>DllGetActivationFactory</c> on
    /// <c>WinRT.Component.dll</c>. JIT consumers reach the merged factory through
    /// <c>WinRT.Host.Shim</c>'s managed reflection path; AOT consumers (or any caller using
    /// <c>LoadLibrary + GetProcAddress</c> directly) need the native export.
    /// </summary>
    private static void WriteNativeExports(ProjectionGeneratorProcessingState processingState)
    {
        const string source = """
            // <auto-generated/>
            #pragma warning disable

            namespace ABI.WinRT.Component;

            using global::System;
            using global::System.Runtime.CompilerServices;
            using global::System.Runtime.InteropServices;
            using global::System.Runtime.Versioning;

            using HRESULT = int;
            using unsafe HSTRING = void*;
            using unsafe IActivationFactory = void*;

            /// <summary>
            /// Native exports on <c>WinRT.Component.dll</c> for AOT consumers. Wraps the merged
            /// managed <see cref="ManagedExports.GetActivationFactory(ReadOnlySpan{char})"/>.
            /// </summary>
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            internal static unsafe class NativeExports
            {
                /// <see href="https://learn.microsoft.com/en-us/previous-versions/br205771(v=vs.85)"/>
                [UnmanagedCallersOnly(EntryPoint = nameof(DllGetActivationFactory), CallConvs = [typeof(CallConvStdcall)])]
                public static HRESULT DllGetActivationFactory(HSTRING activatableClassId, IActivationFactory* factory)
                {
                    const int E_INVALIDARG = unchecked((int)0x80070057);
                    const int CLASS_E_CLASSNOTAVAILABLE = unchecked((int)(0x80040111));
                    const int S_OK = 0;

                    if (activatableClassId is null || factory is null)
                    {
                        return E_INVALIDARG;
                    }

                    ReadOnlySpan<char> managedActivatableClassId = HStringMarshaller.ConvertToManagedUnsafe(activatableClassId);

                    try
                    {
                        IActivationFactory result = ManagedExports.GetActivationFactory(managedActivatableClassId);

                        if ((void*)result is null)
                        {
                            *factory = null;

                            return CLASS_E_CLASSNOTAVAILABLE;
                        }

                        *factory = (void*)result;

                        return S_OK;
                    }
                    catch (Exception e)
                    {
                        return Marshal.GetHRForException(e);
                    }
                }

                /// <see href="https://learn.microsoft.com/en-us/windows/win32/api/combaseapi/nf-combaseapi-dllcanunloadnow"/>
                [UnmanagedCallersOnly(EntryPoint = nameof(DllCanUnloadNow), CallConvs = [typeof(CallConvStdcall)])]
                public static HRESULT DllCanUnloadNow()
                {
                    const HRESULT S_FALSE = 1;

                    return S_FALSE;
                }
            }

            file static class HStringMarshaller
            {
                public static unsafe ReadOnlySpan<char> ConvertToManagedUnsafe(HSTRING value)
                {
                    uint length;
                    char* buffer = WindowsRuntimeImports.WindowsGetStringRawBuffer(value, &length);

                    return new(buffer, (int)length);
                }
            }

            file static class WindowsRuntimeImports
            {
                /// <see href="https://learn.microsoft.com/windows/win32/api/winstring/nf-winstring-windowsgetstringrawbuffer"/>
                [DllImport("api-ms-win-core-winrt-string-l1-1-0.dll", EntryPoint = "WindowsGetStringRawBuffer", ExactSpelling = true)]
                [SupportedOSPlatform("windows6.2")]
                public static unsafe extern char* WindowsGetStringRawBuffer(HSTRING @string, uint* length);
            }
            """;

        File.WriteAllText(Path.Combine(processingState.SourcesFolder, "NativeExports.g.cs"), source);
    }
}
