// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System;
using System.IO;
using System.Text;
using AsmResolver.DotNet;

namespace WindowsRuntime.ProjectionGenerator.Generation;

/// <inheritdoc cref="ProjectionGenerator"/>
internal partial class ProjectionGenerator
{
    /// <summary>
    /// Component-mode only. Emits the auxiliary source files for <c>WinRT.Component.dll</c>:
    /// (a) a module initializer that designates this assembly as the entry assembly for
    /// .NET TypeMap discovery, (b) a <c>[TypeMapAssemblyTarget]</c> union covering each
    /// component plus shared infrastructure assemblies, (c) a merged
    /// <c>ABI.WinRT.Component.ManagedExports.GetActivationFactory</c> that the
    /// <c>WinRT.Host.Shim</c> reflects on, and (d, AOT only) a C-callable
    /// <c>DllGetActivationFactory</c> export wrapping the merged factory.
    /// </summary>
    /// <remarks>
    /// These emissions write directly into <see cref="ProjectionGeneratorProcessingState.SourcesFolder"/>
    /// (the same folder cswinrt.exe targets), so they are picked up automatically by the
    /// Roslyn compile step in <see cref="Emit"/>.
    /// </remarks>
    private static void EmitAuxiliaryComponentSources(ProjectionGeneratorArgs args, ProjectionGeneratorProcessingState processingState)
    {
        // Only emit these files when producing 'WinRT.Component.dll'.
        if (args.AssemblyName != "WinRT.Component")
        {
            return;
        }

        // Nothing to merge if there are no input components. cswinrt.exe -component would
        // not have produced any 'ABI.{ComponentName}.ManagedExports' types either.
        if (processingState.ComponentAssemblyNames.Count == 0)
        {
            return;
        }

        WriteProjectionTypesInitializer(processingState);
        WriteTypeMapAssemblyTargets(args, processingState);
        WriteMergedManagedExports(processingState);

        if (args.PublishAot)
        {
            WriteNativeExports(processingState);
        }
    }

    /// <summary>
    /// Emits a <c>[ModuleInitializer]</c>-driven <c>SetEntryAssembly</c> in <c>WinRT.Component.dll</c>.
    /// This designates <c>WinRT.Component.dll</c> as the entry assembly the .NET runtime uses
    /// to root <c>[TypeMapAssemblyTarget]</c> discovery. The runtime side ensures
    /// <c>WinRT.Component.dll</c> loads first (so this initializer fires before per-component
    /// module initializers), and the check is idempotent so any later per-component module
    /// initializer (which is also idempotent in the new design) is a no-op.
    /// </summary>
    private static void WriteProjectionTypesInitializer(ProjectionGeneratorProcessingState processingState)
    {
        const string source = """
            // <auto-generated/>
            #pragma warning disable

            namespace ABI.WinRT.Component;

            /// <summary>
            /// Designates <c>WinRT.Component.dll</c> as the entry assembly for the hosted .NET
            /// runtime so that <c>[TypeMapAssemblyTarget]</c> discovery (rooted at the entry
            /// assembly) sees the union assembly attributes emitted on this dll.
            /// </summary>
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            internal static class ProjectionTypesInitializer
            {
            #pragma warning disable CA2255 // The 'ModuleInitializer' attribute should not be used in libraries
                [global::System.Runtime.CompilerServices.ModuleInitializer]
            #pragma warning restore CA2255
                internal static void InitializeProjectionTypes()
                {
                    if (global::System.Reflection.Assembly.GetEntryAssembly() is null)
                    {
                        global::System.Reflection.Assembly.SetEntryAssembly(typeof(ProjectionTypesInitializer).Assembly);
                    }
                }
            }
            """;

        File.WriteAllText(Path.Combine(processingState.SourcesFolder, "ProjectionTypesInitializer.g.cs"), source);
    }

    /// <summary>
    /// Emits the union <c>[TypeMapAssemblyTarget]</c> assembly attributes on
    /// <c>WinRT.Component.dll</c>. The union covers each input component, the shared CsWinRT
    /// infrastructure assemblies (<c>WinRT.Interop</c>, <c>WinRT.Runtime</c>,
    /// <c>WinRT.Sdk.Projection</c>), and (when applicable) <c>WinRT.Sdk.Xaml.Projection</c>
    /// and <c>WinRT.Projection</c>.
    /// </summary>
    /// <remarks>
    /// Only assemblies that will actually be deployed alongside <c>WinRT.Component.dll</c> are
    /// included. The .NET runtime fails with <see cref="FileNotFoundException"/> when it tries
    /// to enumerate a target assembly that doesn't exist, which would in turn fail the static
    /// constructor of any type that depends on the type map (e.g. <c>WindowsRuntimeComWrappers</c>).
    /// </remarks>
    private static void WriteTypeMapAssemblyTargets(ProjectionGeneratorArgs args, ProjectionGeneratorProcessingState processingState)
    {
        // Build the list of target assembly simple names. Order is deterministic for stable
        // codegen output. The runtime treats the order as irrelevant for discovery.
        System.Collections.Generic.List<string> targetAssemblyNames =
        [
            "WinRT.Interop",
            "WinRT.Runtime",
            "WinRT.Sdk.Projection",
        ];

        if (args.WindowsUIXamlProjection)
        {
            targetAssemblyNames.Add("WinRT.Sdk.Xaml.Projection");
        }

        // 'WinRT.Projection.dll' is generated only when there are non-Windows-SDK, non-component
        // Windows Runtime reference assemblies in scope (i.e. third-party projection references).
        // Only include it in the union when that condition holds; otherwise the runtime would
        // fail with FileNotFoundException trying to enumerate a non-existent assembly.
        if (HasMergedProjectionReferences(args, processingState))
        {
            targetAssemblyNames.Add("WinRT.Projection");
        }

        // Per-component targets
        targetAssemblyNames.AddRange(processingState.ComponentAssemblyNames);

        StringBuilder sb = new();
        _ = sb.AppendLine("// <auto-generated/>");
        _ = sb.AppendLine("#pragma warning disable");
        _ = sb.AppendLine();

        foreach (string targetTypeMapGroup in (string[])
        [
            "global::WindowsRuntime.InteropServices.WindowsRuntimeComWrappersTypeMapGroup",
            "global::WindowsRuntime.InteropServices.WindowsRuntimeMetadataTypeMapGroup",
            "global::WindowsRuntime.InteropServices.DynamicInterfaceCastableImplementationTypeMapGroup",
        ])
        {
            foreach (string targetAssembly in targetAssemblyNames)
            {
                _ = sb.Append("[assembly: global::System.Runtime.InteropServices.TypeMapAssemblyTarget<")
                       .Append(targetTypeMapGroup)
                       .Append(">(\"")
                       .Append(targetAssembly)
                       .AppendLine("\")]");
            }

            _ = sb.AppendLine();
        }

        File.WriteAllText(Path.Combine(processingState.SourcesFolder, "TypeMapAssemblyTargets.g.cs"), sb.ToString());
    }

    /// <summary>
    /// Returns <c>true</c> if there is at least one non-Windows-SDK, non-component Windows Runtime
    /// reference assembly in scope - i.e. the same condition the merged projection target
    /// uses to determine whether <c>WinRT.Projection.dll</c> needs to be generated.
    /// </summary>
    private static bool HasMergedProjectionReferences(ProjectionGeneratorArgs args, ProjectionGeneratorProcessingState processingState)
    {
        _ = processingState;
        string[] resolverPaths = [.. System.Linq.Enumerable.Where(args.ReferenceAssemblyPaths,
            p => !p.EndsWith(".winmd", StringComparison.OrdinalIgnoreCase))];

        PathAssemblyResolver resolver = new(resolverPaths);

        foreach (string refPath in args.ReferenceAssemblyPaths)
        {
            if (refPath.EndsWith(".winmd", StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            ModuleDefinition refModule;

            try
            {
                refModule = ModuleDefinition.FromFile(refPath, resolver.ReaderParameters);
            }
            catch
            {
                continue;
            }

            // Skip non-projection references (only WinRT projection .dll-s are interesting)
            if (!IsReferenceAssembly(refModule) || !IsWindowsRuntimeReferenceAssembly(refModule))
            {
                continue;
            }

            // Windows SDK projections (Microsoft.Windows.SDK.NET / Microsoft.Windows.UI.Xaml)
            // go into 'WinRT.Sdk.Projection.dll' / 'WinRT.Sdk.Xaml.Projection.dll', not 'WinRT.Projection.dll'.
            if (IsWindowsSdkAssembly(refModule))
            {
                continue;
            }

            // Component reference projections also don't go into 'WinRT.Projection.dll' (they
            // are listed separately in the per-component target group above).
            if (IsComponentAssembly(refModule))
            {
                continue;
            }

            // A third-party Windows Runtime reference projection - 'WinRT.Projection.dll' will
            // be generated by '_RunCsWinRTMergedProjectionGenerator' for these.
            return true;
        }

        return false;
    }

    /// <summary>
    /// Emits <c>ABI.WinRT.Component.ManagedExports.GetActivationFactory</c>: a merged
    /// activation dispatcher in <c>WinRT.Component.dll</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The dispatcher first tries to short-circuit by inspecting the first segment of the
    /// requested runtime class name (e.g. <c>"Foo"</c> from <c>"Foo.Bar.Type"</c>) and
    /// matching it against the set of top-level namespace tokens contributed by each
    /// input component (collected during winmd processing). When the first segment matches
    /// exactly one component, only that component's
    /// <c>ABI.{ComponentName}.ManagedExports.GetActivationFactory</c> is invoked - i.e.
    /// O(1) component selection rather than O(N) linear iteration.
    /// </para>
    /// <para>
    /// If the first segment doesn't uniquely identify a component (no match, or shared
    /// across multiple components), the dispatcher falls back to walking every component's
    /// <c>ManagedExports</c> in turn. This preserves correctness for edge cases.
    /// </para>
    /// <para>
    /// This is what <c>WinRT.Host.Shim.GetActivationFactory</c> reflects on when the loaded
    /// target assembly is <c>WinRT.Component.dll</c> (the shim computes a moduleName of
    /// <c>"WinRT.Component"</c> from the dll filename and looks up
    /// <c>ABI.WinRT.Component.ManagedExports</c>).
    /// </para>
    /// </remarks>
    private static void WriteMergedManagedExports(ProjectionGeneratorProcessingState processingState)
    {
        // Build first-segment -> components map. A first segment that maps to exactly one
        // component is a candidate for the prefix-dispatch fast path; segments shared by
        // multiple components require the linear-walk fallback (to allow each candidate to
        // claim the class).
        System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> segmentOwners =
            new(System.StringComparer.Ordinal);

        foreach (string componentName in processingState.ComponentAssemblyNames)
        {
            if (!processingState.ComponentNamespacePrefixes.TryGetValue(componentName, out System.Collections.Generic.IReadOnlyList<string>? prefixes))
            {
                continue;
            }

            foreach (string prefix in prefixes)
            {
                if (!segmentOwners.TryGetValue(prefix, out System.Collections.Generic.List<string>? owners))
                {
                    owners = [];
                    segmentOwners[prefix] = owners;
                }

                owners.Add(componentName);
            }
        }

        // Sort segments for stable codegen output.
        System.Collections.Generic.List<string> sortedSegments = [.. segmentOwners.Keys];
        sortedSegments.Sort(System.StringComparer.Ordinal);

        StringBuilder sb = new();

        _ = sb.AppendLine("// <auto-generated/>");
        _ = sb.AppendLine("#pragma warning disable");
        _ = sb.AppendLine();
        _ = sb.AppendLine("namespace ABI.WinRT.Component;");
        _ = sb.AppendLine();
        _ = sb.AppendLine("/// <summary>");
        _ = sb.AppendLine("/// Merged managed activation entry point for <c>WinRT.Component.dll</c>. Reflectively");
        _ = sb.AppendLine("/// invoked by <c>WinRT.Host.Shim.GetActivationFactory</c>; routes by first-segment");
        _ = sb.AppendLine("/// namespace to the owning component's <c>ManagedExports</c>, with a linear-walk");
        _ = sb.AppendLine("/// fallback for unknown segments or segments shared across multiple components.");
        _ = sb.AppendLine("/// </summary>");
        _ = sb.AppendLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        _ = sb.AppendLine("public static unsafe class ManagedExports");
        _ = sb.AppendLine("{");
        _ = sb.AppendLine("    public static void* GetActivationFactory(global::System.ReadOnlySpan<char> activatableClassId)");
        _ = sb.AppendLine("    {");

        // Try first-segment dispatch when the segment uniquely identifies a single component.
        bool hasFastPath = false;

        foreach (string segment in sortedSegments)
        {
            System.Collections.Generic.List<string> owners = segmentOwners[segment];

            if (owners.Count != 1)
            {
                continue;
            }

            if (!hasFastPath)
            {
                _ = sb.AppendLine("        // Fast path: when the runtime class name's first segment uniquely identifies");
                _ = sb.AppendLine("        // one component, dispatch directly to that component's ManagedExports.");
                _ = sb.AppendLine("        int dotIndex = global::System.MemoryExtensions.IndexOf(activatableClassId, '.');");
                _ = sb.AppendLine("        global::System.ReadOnlySpan<char> firstSegment = dotIndex < 0 ? activatableClassId : activatableClassId.Slice(0, dotIndex);");
                _ = sb.AppendLine();
                _ = sb.Append("        switch (firstSegment)");
                _ = sb.AppendLine();
                _ = sb.AppendLine("        {");
                hasFastPath = true;
            }

            _ = sb.Append("            case \"")
                   .Append(segment)
                   .Append("\": return global::ABI.")
                   .Append(owners[0])
                   .AppendLine(".ManagedExports.GetActivationFactory(activatableClassId);");
        }

        if (hasFastPath)
        {
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine();
        }

        // Fallback path: walk all components in order. Hit either when the first-segment
        // didn't match any case above (unknown namespace) or when a segment is shared
        // across multiple components (so we can't uniquely route).
        if (processingState.ComponentAssemblyNames.Count > 0)
        {
            _ = sb.AppendLine("        // Fallback: linear walk for unknown or ambiguous first segments.");
            _ = sb.AppendLine("        void* factory;");

            foreach (string componentName in processingState.ComponentAssemblyNames)
            {
                _ = sb.AppendLine();
                _ = sb.Append("        factory = global::ABI.")
                       .Append(componentName)
                       .AppendLine(".ManagedExports.GetActivationFactory(activatableClassId);");
                _ = sb.AppendLine("        if (factory is not null)");
                _ = sb.AppendLine("        {");
                _ = sb.AppendLine("            return factory;");
                _ = sb.AppendLine("        }");
            }

            _ = sb.AppendLine();
        }

        _ = sb.AppendLine("        return null;");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    /// <summary>");
        _ = sb.AppendLine("    /// Reflection-friendly overload used by managed runtime hosts (e.g. <c>WinRT.Host.Shim</c>).");
        _ = sb.AppendLine("    /// </summary>");
        _ = sb.AppendLine("    public static nint GetActivationFactory(string activatableClassId)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        return (nint)GetActivationFactory(global::System.MemoryExtensions.AsSpan(activatableClassId));");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine("}");

        File.WriteAllText(Path.Combine(processingState.SourcesFolder, "MergedManagedExports.g.cs"), sb.ToString());
    }

    /// <summary>
    /// (AOT only) Emits the C-callable <c>DllGetActivationFactory</c> on
    /// <c>WinRT.Component.dll</c>. JIT consumers reach the merged factory through
    /// <c>WinRT.Host.Shim</c>'s managed reflection path; AOT consumers (or any caller using
    /// <c>LoadLibrary + GetProcAddress</c> directly) need the native export.
    /// </summary>
    private static void WriteNativeExports(ProjectionGeneratorProcessingState processingState)
    {
        const string source = """
            // <auto-generated/>
            #pragma warning disable

            namespace ABI.WinRT.Component;

            using global::System;
            using global::System.Runtime.CompilerServices;
            using global::System.Runtime.InteropServices;
            using global::System.Runtime.Versioning;

            using HRESULT = int;
            using unsafe HSTRING = void*;
            using unsafe IActivationFactory = void*;

            /// <summary>
            /// Native exports on <c>WinRT.Component.dll</c> for AOT consumers. Wraps the merged
            /// managed <see cref="ManagedExports.GetActivationFactory(ReadOnlySpan{char})"/>.
            /// </summary>
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            internal static unsafe class NativeExports
            {
                /// <see href="https://learn.microsoft.com/en-us/previous-versions/br205771(v=vs.85)"/>
                [UnmanagedCallersOnly(EntryPoint = nameof(DllGetActivationFactory), CallConvs = [typeof(CallConvStdcall)])]
                public static HRESULT DllGetActivationFactory(HSTRING activatableClassId, IActivationFactory* factory)
                {
                    const int E_INVALIDARG = unchecked((int)0x80070057);
                    const int CLASS_E_CLASSNOTAVAILABLE = unchecked((int)(0x80040111));
                    const int S_OK = 0;

                    if (activatableClassId is null || factory is null)
                    {
                        return E_INVALIDARG;
                    }

                    ReadOnlySpan<char> managedActivatableClassId = HStringMarshaller.ConvertToManagedUnsafe(activatableClassId);

                    try
                    {
                        IActivationFactory result = ManagedExports.GetActivationFactory(managedActivatableClassId);

                        if ((void*)result is null)
                        {
                            *factory = null;

                            return CLASS_E_CLASSNOTAVAILABLE;
                        }

                        *factory = (void*)result;

                        return S_OK;
                    }
                    catch (Exception e)
                    {
                        return Marshal.GetHRForException(e);
                    }
                }

                /// <see href="https://learn.microsoft.com/en-us/windows/win32/api/combaseapi/nf-combaseapi-dllcanunloadnow"/>
                [UnmanagedCallersOnly(EntryPoint = nameof(DllCanUnloadNow), CallConvs = [typeof(CallConvStdcall)])]
                public static HRESULT DllCanUnloadNow()
                {
                    const HRESULT S_FALSE = 1;

                    return S_FALSE;
                }
            }

            file static class HStringMarshaller
            {
                public static unsafe ReadOnlySpan<char> ConvertToManagedUnsafe(HSTRING value)
                {
                    uint length;
                    char* buffer = WindowsRuntimeImports.WindowsGetStringRawBuffer(value, &length);

                    return new(buffer, (int)length);
                }
            }

            file static class WindowsRuntimeImports
            {
                /// <see href="https://learn.microsoft.com/windows/win32/api/winstring/nf-winstring-windowsgetstringrawbuffer"/>
                [DllImport("api-ms-win-core-winrt-string-l1-1-0.dll", EntryPoint = "WindowsGetStringRawBuffer", ExactSpelling = true)]
                [SupportedOSPlatform("windows6.2")]
                public static unsafe extern char* WindowsGetStringRawBuffer(HSTRING @string, uint* length);
            }
            """;

        File.WriteAllText(Path.Combine(processingState.SourcesFolder, "NativeExports.g.cs"), source);
    }
}
