<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UseUwp>true</UseUwp>
    <UseUwpTools>false</UseUwpTools>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <IlcResilient>false</IlcResilient>
    <ILLinkTreatWarningsAsErrors>true</ILLinkTreatWarningsAsErrors>
    <SuppressTrimAnalysisWarnings>false</SuppressTrimAnalysisWarnings>
    <SuppressAotAnalysisWarnings>false</SuppressAotAnalysisWarnings>
    <TrimmerSingleWarn>false</TrimmerSingleWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExclusiveToProjection\ExclusiveToProjection.csproj"
                      GlobalPropertiesToRemove="PublishAot;RuntimeIdentifier;SelfContained" />
  </ItemGroup>
</Project>
