variables:
- template: eng\CsWinRT-BuildVariables.yml

name: $(MajorVersion).$(MinorVersion).$(PatchVersion)$(PrereleaseVersion).$(date:yyMMdd)$(rev:.r)

stages:
- template: eng\CsWinRT-Build-Stage.yml

- template: eng\CsWinRT-Test-Stage.yml

- template: eng\CsWinRT-PublishToNuget-Stage.yml

# - template: eng\CsWinRT-WinUIValidation-Stage.yml