// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System;
using System.Collections.Generic;
using System.IO;
using AsmResolver.DotNet;

namespace WindowsRuntime.ProjectionGenerator.Writer;

/// <summary>
/// Helper writers for assembly attributes, metadata attributes, and other infrastructure.
/// Mirrors various functions in <c>code_writers.h</c>.
/// </summary>
internal static partial class CodeWriters
{
    /// <summary>Mirrors C++ <c>write_pragma_disable_IL2026</c>.</summary>
    public static void WritePragmaDisableIL2026(TextWriter w)
    {
        w.Write("\n#pragma warning disable IL2026\n");
    }

    /// <summary>Mirrors C++ <c>write_pragma_restore_IL2026</c>.</summary>
    public static void WritePragmaRestoreIL2026(TextWriter w)
    {
        w.Write("\n#pragma warning restore IL2026\n");
    }

    /// <summary>Mirrors C++ <c>write_file_header</c>.</summary>
    public static void WriteFileHeader(TextWriter w)
    {
        w.Write(@"//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by cswinrt.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
");
    }

    /// <summary>Mirrors C++ <c>write_winrt_metadata_attribute</c>.</summary>
    public static void WriteWinRTMetadataAttribute(TypeWriter w, TypeDefinition type, MetadataCache cache)
    {
        string path = cache.GetSourcePath(type);
        string stem = string.IsNullOrEmpty(path) ? string.Empty : Path.GetFileNameWithoutExtension(path);
        w.Write("[WindowsRuntimeMetadata(\"");
        w.Write(stem);
        w.Write("\")]\n");
    }

    /// <summary>Mirrors C++ <c>write_winrt_metadata_typename_attribute</c>.</summary>
    public static void WriteWinRTMetadataTypeNameAttribute(TypeWriter w, TypeDefinition type)
    {
        w.Write("[WindowsRuntimeMetadataTypeName(\"");
        WriteTypedefName(w, type, TypedefNameType.NonProjected, true);
        WriteTypeParams(w, type);
        w.Write("\")]\n");
    }

    /// <summary>Mirrors C++ <c>write_winrt_mapped_type_attribute</c>.</summary>
    public static void WriteWinRTMappedTypeAttribute(TypeWriter w, TypeDefinition type)
    {
        w.Write("[WindowsRuntimeMappedType(typeof(");
        WriteTypedefName(w, type, TypedefNameType.Projected, true);
        WriteTypeParams(w, type);
        w.Write("))]\n");
    }

    /// <summary>Mirrors C++ <c>write_value_type_winrt_classname_attribute</c>.</summary>
    public static void WriteValueTypeWinRTClassNameAttribute(TypeWriter w, TypeDefinition type)
    {
        if (w.Settings.ReferenceProjection) { return; }
        string ns = type.Namespace?.Value ?? string.Empty;
        string name = type.Name?.Value ?? string.Empty;
        w.Write("[WindowsRuntimeClassName(\"Windows.Foundation.IReference`1<");
        w.Write(ns);
        w.Write(".");
        w.Write(name);
        w.Write(">\")]\n");
    }

    /// <summary>Mirrors C++ <c>write_winrt_reference_type_attribute</c>.</summary>
    public static void WriteWinRTReferenceTypeAttribute(TypeWriter w, TypeDefinition type)
    {
        if (w.Settings.ReferenceProjection) { return; }
        w.Write("[WindowsRuntimeReferenceType(typeof(");
        WriteTypedefName(w, type, TypedefNameType.Projected, false);
        WriteTypeParams(w, type);
        w.Write("?))]\n");
    }

    /// <summary>Mirrors C++ <c>write_comwrapper_marshaller_attribute</c>.</summary>
    public static void WriteComWrapperMarshallerAttribute(TypeWriter w, TypeDefinition type)
    {
        if (w.Settings.ReferenceProjection) { return; }
        string ns = type.Namespace?.Value ?? string.Empty;
        string name = type.Name?.Value ?? string.Empty;
        w.Write("[ABI.");
        w.Write(ns);
        w.Write(".");
        w.Write(Helpers.StripBackticks(name));
        w.Write("ComWrappersMarshaller]\n");
    }

    /// <summary>
    /// Mirrors C++ <c>write_winrt_windowsmetadata_typemapgroup_assembly_attribute</c>.
    /// </summary>
    public static void WriteWinRTWindowsMetadataTypeMapGroupAssemblyAttribute(TypeWriter w, TypeDefinition type)
    {
        // Skip exclusive interfaces and projection-internal interfaces
        if (TypeCategorization.GetCategory(type) == TypeCategory.Interface &&
            (TypeCategorization.IsExclusiveTo(type) || TypeCategorization.IsProjectionInternal(type)))
        {
            return;
        }

        string projectionName = w.WriteTemp("%", new Action<TextWriter>(tw =>
        {
            // Use a temporary TypeWriter for the typedef name with full namespace
            WriteTypedefName(w, type, TypedefNameType.NonProjected, true);
            WriteTypeParams(w, type);
        }));

        w.Write("\n[assembly: TypeMap<WindowsRuntimeMetadataTypeMapGroup>(\n    value: \"");
        w.Write(projectionName);
        w.Write("\",\n    target: typeof(");
        if (w.Settings.Component)
        {
            WriteTypedefName(w, type, TypedefNameType.ABI, true);
            WriteTypeParams(w, type);
        }
        else
        {
            w.Write(projectionName);
        }
        w.Write("),\n    trimTarget: typeof(");
        w.Write(projectionName);
        w.Write("))]\n");

        if (w.Settings.Component)
        {
            w.Write("\n[assembly: TypeMapAssociation<WindowsRuntimeMetadataTypeMapGroup>(\n    source: typeof(");
            w.Write(projectionName);
            w.Write("),\n    proxy: typeof(");
            WriteTypedefName(w, type, TypedefNameType.ABI, true);
            WriteTypeParams(w, type);
            w.Write("))]\n\n");
        }
    }

    /// <summary>
    /// Mirrors C++ <c>write_winrt_comwrappers_typemapgroup_assembly_attribute</c>.
    /// </summary>
    public static void WriteWinRTComWrappersTypeMapGroupAssemblyAttribute(TypeWriter w, TypeDefinition type, bool isValueType)
    {
        string projectionName = w.WriteTemp("%", new Action<TextWriter>(tw =>
        {
            WriteTypedefName(w, type, TypedefNameType.NonProjected, true);
            WriteTypeParams(w, type);
        }));

        w.Write("\n[assembly: TypeMap<WindowsRuntimeComWrappersTypeMapGroup>(\n    value: \"");
        if (isValueType)
        {
            w.Write("Windows.Foundation.IReference`1<");
            w.Write(projectionName);
            w.Write(">");
        }
        else
        {
            w.Write(projectionName);
        }
        w.Write("\",\n    target: typeof(");
        if (w.Settings.Component)
        {
            WriteTypedefName(w, type, TypedefNameType.ABI, true);
            WriteTypeParams(w, type);
        }
        else
        {
            w.Write(projectionName);
        }
        w.Write("),\n    trimTarget: typeof(");
        w.Write(projectionName);
        w.Write("))]\n");

        // For non-interface, non-struct authored types, emit proxy association.
        TypeCategory cat = TypeCategorization.GetCategory(type);
        if (cat != TypeCategory.Interface && cat != TypeCategory.Struct && w.Settings.Component)
        {
            w.Write("\n[assembly: TypeMapAssociation<WindowsRuntimeComWrappersTypeMapGroup>(\n    source: typeof(");
            w.Write(projectionName);
            w.Write("),\n    proxy: typeof(");
            WriteTypedefName(w, type, TypedefNameType.ABI, true);
            WriteTypeParams(w, type);
            w.Write("))]\n\n");
        }
    }

    /// <summary>
    /// Mirrors C++ <c>write_winrt_idic_typemapgroup_assembly_attribute</c>.
    /// </summary>
    public static void WriteWinRTIdicTypeMapGroupAssemblyAttribute(TypeWriter w, TypeDefinition type)
    {
        // Generic interfaces are handled elsewhere
        if (type.GenericParameters.Count != 0) { return; }
        // Skip exclusive interfaces (unless idic_exclusiveto), and projection-internal
        if ((TypeCategorization.IsExclusiveTo(type) && !w.Settings.IdicExclusiveTo) ||
            TypeCategorization.IsProjectionInternal(type))
        {
            return;
        }

        w.Write("\n[assembly: TypeMapAssociation<DynamicInterfaceCastableImplementationTypeMapGroup>(\n    source: typeof(");
        WriteTypedefName(w, type, TypedefNameType.Projected, true);
        WriteTypeParams(w, type);
        w.Write("),\n    proxy: typeof(");
        WriteTypedefName(w, type, TypedefNameType.ABI, true);
        WriteTypeParams(w, type);
        w.Write("))]\n\n");
    }

    /// <summary>
    /// Adds an entry to the default-interface map for a class type.
    /// Mirrors C++ <c>add_default_interface_entry</c>.
    /// </summary>
    public static void AddDefaultInterfaceEntry(TypeWriter w, TypeDefinition type, System.Collections.Concurrent.ConcurrentDictionary<string, string> entries)
    {
        if (w.Settings.ReferenceProjection) { return; }
        ITypeDefOrRef? defaultIface = Helpers.GetDefaultInterface(type);
        if (defaultIface is null) { return; }

        string typeNs = type.Namespace?.Value ?? string.Empty;
        string typeName = type.Name?.Value ?? string.Empty;
        string className = $"global::{typeNs}.{Helpers.StripBackticks(typeName)}";

        // Resolve the interface to write its CCW name. For TypeRefs, fall back to plain namespace.name.
        string interfaceName;
        TypeDefinition? ifaceDef = defaultIface as TypeDefinition;
        if (ifaceDef is null && defaultIface is TypeReference ifaceRef)
        {
            string ins = ifaceRef.Namespace?.Value ?? string.Empty;
            string inm = ifaceRef.Name?.Value ?? string.Empty;
            // Apply mapped-type remapping (e.g. IClosable -> System.IDisposable)
            MappedType? mapped = MappedTypes.Get(ins, inm);
            if (mapped is not null)
            {
                ins = mapped.MappedNamespace;
                inm = mapped.MappedName;
            }
            interfaceName = $"global::{ins}.{Helpers.StripBackticks(inm)}";
        }
        else if (ifaceDef is not null)
        {
            // Apply mapped-type remapping
            string ins = ifaceDef.Namespace?.Value ?? string.Empty;
            string inm = ifaceDef.Name?.Value ?? string.Empty;
            MappedType? mappedDef = MappedTypes.Get(ins, inm);
            if (mappedDef is not null)
            {
                interfaceName = $"global::{mappedDef.MappedNamespace}.{Helpers.StripBackticks(mappedDef.MappedName)}";
            }
            else
            {
                TypeDefinition capturedIface = ifaceDef;
                interfaceName = w.WriteTemp("%", new Action<TextWriter>(tw =>
                {
                    WriteTypedefName(w, capturedIface, TypedefNameType.CCW, true);
                    WriteTypeParams(w, capturedIface);
                }));
            }
        }
        else
        {
            return;
        }

        _ = entries.TryAdd(className, interfaceName);
    }

    /// <summary>
    /// Adds entries for [ExclusiveTo] interfaces of the class type.
    /// Mirrors C++ <c>add_exclusive_to_interface_entries</c>.
    /// </summary>
    public static void AddExclusiveToInterfaceEntries(TypeWriter w, TypeDefinition type, System.Collections.Concurrent.ConcurrentBag<KeyValuePair<string, string>> entries)
    {
        if (!w.Settings.Component || w.Settings.ReferenceProjection) { return; }
        string typeNs = type.Namespace?.Value ?? string.Empty;
        string typeName = type.Name?.Value ?? string.Empty;
        string className = $"global::{typeNs}.{Helpers.StripBackticks(typeName)}";

        foreach (InterfaceImplementation impl in type.Interfaces)
        {
            if (impl.Interface is null) { continue; }
            TypeDefinition? ifaceDef = impl.Interface as TypeDefinition;
            if (ifaceDef is null) { continue; }
            if (TypeCategorization.IsExclusiveTo(ifaceDef))
            {
                string interfaceName = w.WriteTemp("%", new Action<TextWriter>(tw =>
                {
                    WriteTypedefName(w, ifaceDef, TypedefNameType.CCW, true);
                    WriteTypeParams(w, ifaceDef);
                }));
                entries.Add(new KeyValuePair<string, string>(className, interfaceName));
            }
        }
    }

    /// <summary>Writes the generated WindowsRuntimeDefaultInterfaces.cs file (mirrors C++ <c>write_default_interfaces_class</c>).</summary>
    public static void WriteDefaultInterfacesClass(Settings settings, IReadOnlyList<KeyValuePair<string, string>> sortedEntries)
    {
        if (sortedEntries.Count == 0) { return; }
        TextWriter w = new();
        WriteFileHeader(w);
        w.Write("using System;\nusing WindowsRuntime;\n\n#pragma warning disable CSWINRT3001\n\nnamespace ABI\n{\n");
        foreach (KeyValuePair<string, string> kv in sortedEntries)
        {
            w.Write("[WindowsRuntimeDefaultInterface(typeof(");
            w.Write(kv.Key);
            w.Write("), typeof(");
            w.Write(kv.Value);
            w.Write("))]\n");
        }
        w.Write("internal static class WindowsRuntimeDefaultInterfaces;\n}\n");
        w.FlushToFile(Path.Combine(settings.OutputFolder, "WindowsRuntimeDefaultInterfaces.cs"));
    }

    /// <summary>Writes the generated WindowsRuntimeExclusiveToInterfaces.cs file (mirrors C++ <c>write_exclusive_to_interfaces_class</c>).</summary>
    public static void WriteExclusiveToInterfacesClass(Settings settings, IReadOnlyList<KeyValuePair<string, string>> sortedEntries)
    {
        if (sortedEntries.Count == 0) { return; }
        TextWriter w = new();
        WriteFileHeader(w);
        w.Write("using System;\nusing WindowsRuntime;\n\n#pragma warning disable CSWINRT3001\n\nnamespace ABI\n{\n");
        foreach (KeyValuePair<string, string> kv in sortedEntries)
        {
            w.Write("[WindowsRuntimeExclusiveToInterface(typeof(");
            w.Write(kv.Key);
            w.Write("), typeof(");
            w.Write(kv.Value);
            w.Write("))]\n");
        }
        w.Write("internal static class WindowsRuntimeExclusiveToInterfaces;\n}\n");
        w.FlushToFile(Path.Combine(settings.OutputFolder, "WindowsRuntimeExclusiveToInterfaces.cs"));
    }
}
