// Modern IDL 3.0: https://docs.microsoft.com/en-us/uwp/midl-3/intro

// Definitions for testing C# runtime class hosting, not implemented in TestComponentCSharp
namespace TestHost
{
    runtimeclass ManagedClass : [default] Windows.Foundation.IStringable
    {
        ManagedClass();
    }

    runtimeclass ManagedClassNotFound : [default] Windows.Foundation.IStringable
    {
        ManagedClassNotFound();
    }
}
