// Modern IDL 3.0: https://docs.microsoft.com/en-us/uwp/midl-3/intro

// Definitions for testing C# runtime class hosting
namespace TestHost
{
    runtimeclass ProbeByClass : [default] Windows.Foundation.IStringable
    {
        ProbeByClass();
    }

    runtimeclass ProbeByHost : [default] Windows.Foundation.IStringable
    {
        ProbeByHost();
    }

    runtimeclass ClassNotFound : [default] Windows.Foundation.IStringable
    {
        ClassNotFound();
    }
}
