<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(DotNetVersion)</TargetFramework>
    <Nullable>enable</Nullable>

    <!-- Common metadata properties for publishing -->
    <Description>C#/WinRT Generator core shared infrastructure v$(VersionString)</Description>
    <AssemblyTitle>C#/WinRT Generator core shared infrastructure v$(VersionString)</AssemblyTitle>
    <Copyright>Copyright (c) Microsoft Corporation. All rights reserved.</Copyright>
    <AssemblyVersion>$(AssemblyVersionNumber)</AssemblyVersion>
    <FileVersion>$(VersionNumber)</FileVersion>

    <!-- Set the root namespace (we ignore the '.Core' suffix) -->
    <RootNamespace>WindowsRuntime.Generator</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AsmResolver.DotNet" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="cswinrtimplgen" />
    <InternalsVisibleTo Include="cswinrtinteropgen" />
    <InternalsVisibleTo Include="cswinrtprojectiongen" />
    <InternalsVisibleTo Include="cswinrtprojectionrefgen" />
    <InternalsVisibleTo Include="cswinrtwinmdgen" />
  </ItemGroup>
</Project>
