// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System;

namespace WindowsRuntime.InteropServices;

/// <summary>
/// An <see cref="EventSource{T}"/> implementation for <see cref="EventHandler{TSender, TEventArgs}"/>.
/// </summary>
/// <typeparam name="TSender">The type of object raising the event.</typeparam>
/// <typeparam name="TEventArgs">The type of the event data generated by the event.</typeparam>
public abstract unsafe class EventHandlerEventSource<TSender, TEventArgs> : EventSource<EventHandler<TSender, TEventArgs>>
{
    /// <inheritdoc cref="EventSource{T}.EventSource"/>
    protected EventHandlerEventSource(WindowsRuntimeObjectReference nativeObjectReference, int index)
        : base(nativeObjectReference, index)
    {
    }

    /// <inheritdoc/>
    protected sealed override EventSourceState<EventHandler<TSender, TEventArgs>> CreateEventSourceState()
    {
        return new EventState(GetNativeObjectReferenceThisPtrUnsafe(), Index);
    }

    /// <summary>
    /// The <see cref="EventSourceState{T}"/> implementation for <see cref="EventHandlerEventSource{T}"/>.
    /// </summary>
    private sealed class EventState : EventSourceState<EventHandler<TSender, TEventArgs>>
    {
        /// <inheritdoc cref="EventSourceState{T}.EventSourceState"/>
        public EventState(void* thisPtr, int index)
            : base(thisPtr, index)
        {
        }

        /// <inheritdoc/>
        protected override EventHandler<TSender, TEventArgs> GetEventInvoke()
        {
            return (obj, e) => TargetDelegate?.Invoke(obj, e);
        }
    }
}
