<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <UseUwp>true</UseUwp>
    <UseUwpTools>false</UseUwpTools>
    <CsWinRTGenerateReferenceProjection>true</CsWinRTGenerateReferenceProjection>
    <CsWinRTIncludes>Windows.UI.Xaml.IFrameworkElementProtected7</CsWinRTIncludes>
    <CsWinRTPublicExclusiveToInterfaces>true</CsWinRTPublicExclusiveToInterfaces>
    <CsWinRTDynamicallyInterfaceCastableExclusiveTo>true</CsWinRTDynamicallyInterfaceCastableExclusiveTo>
  </PropertyGroup>

  <!-- The interface is in the Windows SDK. No package-owned WinMD inputs are needed. -->
</Project>
