// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using WindowsRuntime.SourceGenerator.Tests.Helpers;

namespace WindowsRuntime.SourceGenerator.Tests;

/// <summary>
/// Tests for <see cref="AuthoringExportTypesGenerator"/> in the <c>CsWinRTImplementWinMDTypes</c> authoring
/// mode, where the Windows Runtime type being implemented is declared in an existing <c>.winmd</c>.
/// </summary>
/// <remarks>
/// The sources below declare the abstract bases that the projection writer would have generated into the
/// referenced projection (see <c>AbiImplementableClassFactory</c>), because that is exactly what the user's
/// compilation sees. The runtime class name the exports dispatch on comes from those bases, not from the
/// C# type the user wrote, which is the behavior these tests lock down.
/// </remarks>
[TestClass]
public class Test_AuthoringExportTypesGenerator
{
    [TestMethod]
    public void ImplementableClass_DispatchesOnWindowsRuntimeClassName()
    {
        const string source = """
            using WindowsRuntime;
            using WindowsRuntime.InteropServices;

            namespace Contoso.Widgets
            {
                // The projected runtime class, from the '.winmd'
                public sealed class Widget;
            }

            namespace ABI.Contoso.Widgets
            {
                [WindowsRuntimeImplementableClass(typeof(global::Contoso.Widgets.Widget))]
                public abstract class Widget
                {
                    public abstract void DoStuff();
                }

                [WindowsRuntimeImplementableClassFactory(typeof(global::Contoso.Widgets.Widget))]
                public abstract class WidgetActivationFactory : IActivationFactory
                {
                    public abstract object ActivateInstance();

                    public static nint GetActivationFactoryUnsafe(WidgetActivationFactory value) => throw null!;
                }
            }

            namespace MyApp
            {
                public sealed class MyWidget : global::ABI.Contoso.Widgets.Widget
                {
                    public override void DoStuff() { }
                }

                [WindowsRuntimeActivationFactory(typeof(MyWidget))]
                public sealed class MyWidgetFactory : global::ABI.Contoso.Widgets.WidgetActivationFactory
                {
                    public override object ActivateInstance() => new MyWidget();
                }
            }
            """;

        const string result = """
            // <auto-generated/>
            #pragma warning disable

            [assembly: global::WindowsRuntime.InteropServices.WindowsRuntimeComponentAssembly]
            [assembly: global::WindowsRuntime.InteropServices.WindowsRuntimeComponentAssemblyExportsType(typeof(global::ABI.original.ManagedExports))]

            namespace ABI.original;

            using global::System;
            using global::System.CodeDom.Compiler;
            using global::System.ComponentModel;
            using global::System.Diagnostics;
            using global::System.Diagnostics.CodeAnalysis;
            using global::System.Runtime.CompilerServices;

            /// <summary>
            /// Contains the managed exports for activating types from the current project in an authoring scenario.
            /// </summary>
            [GeneratedCode("AuthoringExportTypesGenerator", <ASSEMBLY_VERSION>)]
            [DebuggerNonUserCode]
            [ExcludeFromCodeCoverage]
            [EditorBrowsable(EditorBrowsableState.Never)]
            public static unsafe class ManagedExports
            {
                private static readonly global::MyApp.MyWidgetFactory _activationFactory_Contoso_Widgets_Widget = new();

                /// <summary>
                /// Retrieves the activation factory from a DLL that contains activatable Windows Runtime classes.
                /// </summary>
                /// <param name="activatableClassId">The class identifier that is associated with an activatable runtime class.</param>
                /// <returns>The resulting pointer to the activation factory that corresponds with the class specified by <paramref name="activatableClassId"/>.</returns>
                public static void* GetActivationFactory(ReadOnlySpan<char> activatableClassId)
                {
                    if (activatableClassId.SequenceEqual("Contoso.Widgets.Widget".AsSpan()))
                    {
                        return (void*)global::ABI.Contoso.Widgets.WidgetActivationFactory.GetActivationFactoryUnsafe(_activationFactory_Contoso_Widgets_Widget);
                    }

                    return null;
                }

                /// <inheritdoc cref="GetActivationFactory(ReadOnlySpan{char})"/>
                /// <remarks>This overload uses reflection friendly types and is only meant to be used from managed runtime hosts.</remarks>
                public static nint GetActivationFactory(string activatableClassId)
                {
                    return (nint)GetActivationFactory(activatableClassId.AsSpan());
                }
            }
            """;

        CSharpGeneratorTest<AuthoringExportTypesGenerator>.VerifySources(source, ("ManagedExports.g.cs", result));
    }

    [TestMethod]
    public void StaticsOnlyClass_ResolvesNameFromFactoryBase()
    {
        // A statics-only runtime class has no instance type, so the runtime class name can only come from
        // the factory base. This is why discovery prefers it over the '[WindowsRuntimeActivationFactory]'
        // argument, which here deliberately points at the factory itself.
        const string source = """
            using WindowsRuntime;
            using WindowsRuntime.InteropServices;

            namespace Contoso.Widgets
            {
                public static class WidgetUtils;
            }

            namespace ABI.Contoso.Widgets
            {
                [WindowsRuntimeImplementableClassFactory(typeof(global::Contoso.Widgets.WidgetUtils))]
                public abstract class WidgetUtilsActivationFactory
                {
                    public abstract int Compute();

                    public static nint GetActivationFactoryUnsafe(WidgetUtilsActivationFactory value) => throw null!;
                }
            }

            namespace MyApp
            {
                [WindowsRuntimeActivationFactory(typeof(MyWidgetUtilsFactory))]
                public sealed class MyWidgetUtilsFactory : global::ABI.Contoso.Widgets.WidgetUtilsActivationFactory
                {
                    public override int Compute() => 42;
                }
            }
            """;

        const string result = """
            // <auto-generated/>
            #pragma warning disable

            [assembly: global::WindowsRuntime.InteropServices.WindowsRuntimeComponentAssembly]
            [assembly: global::WindowsRuntime.InteropServices.WindowsRuntimeComponentAssemblyExportsType(typeof(global::ABI.original.ManagedExports))]

            namespace ABI.original;

            using global::System;
            using global::System.CodeDom.Compiler;
            using global::System.ComponentModel;
            using global::System.Diagnostics;
            using global::System.Diagnostics.CodeAnalysis;
            using global::System.Runtime.CompilerServices;

            /// <summary>
            /// Contains the managed exports for activating types from the current project in an authoring scenario.
            /// </summary>
            [GeneratedCode("AuthoringExportTypesGenerator", <ASSEMBLY_VERSION>)]
            [DebuggerNonUserCode]
            [ExcludeFromCodeCoverage]
            [EditorBrowsable(EditorBrowsableState.Never)]
            public static unsafe class ManagedExports
            {
                private static readonly global::MyApp.MyWidgetUtilsFactory _activationFactory_Contoso_Widgets_WidgetUtils = new();

                /// <summary>
                /// Retrieves the activation factory from a DLL that contains activatable Windows Runtime classes.
                /// </summary>
                /// <param name="activatableClassId">The class identifier that is associated with an activatable runtime class.</param>
                /// <returns>The resulting pointer to the activation factory that corresponds with the class specified by <paramref name="activatableClassId"/>.</returns>
                public static void* GetActivationFactory(ReadOnlySpan<char> activatableClassId)
                {
                    if (activatableClassId.SequenceEqual("Contoso.Widgets.WidgetUtils".AsSpan()))
                    {
                        return (void*)global::ABI.Contoso.Widgets.WidgetUtilsActivationFactory.GetActivationFactoryUnsafe(_activationFactory_Contoso_Widgets_WidgetUtils);
                    }

                    return null;
                }

                /// <inheritdoc cref="GetActivationFactory(ReadOnlySpan{char})"/>
                /// <remarks>This overload uses reflection friendly types and is only meant to be used from managed runtime hosts.</remarks>
                public static nint GetActivationFactory(string activatableClassId)
                {
                    return (nint)GetActivationFactory(activatableClassId.AsSpan());
                }
            }
            """;

        CSharpGeneratorTest<AuthoringExportTypesGenerator>.VerifySources(source, ("ManagedExports.g.cs", result));
    }

    [TestMethod]
    public void FactoryWithoutGeneratedBase_IsNotRegistered()
    {
        // A factory that does not extend a generated base cannot supply 'GetActivationFactoryUnsafe', so it
        // is skipped. With no factories left, the managed exports are not emitted at all.
        const string source = """
            using WindowsRuntime.InteropServices;

            namespace MyApp
            {
                public sealed class MyWidget;

                [WindowsRuntimeActivationFactory(typeof(MyWidget))]
                public sealed class MyWidgetFactory : IActivationFactory
                {
                    public object ActivateInstance() => new MyWidget();
                }
            }
            """;

        CSharpGeneratorTest<AuthoringExportTypesGenerator>.VerifyNoSource(source, "ManagedExports.g.cs");
    }
}
